export interface CanonicalEntity {
  id: string;
  name: string;
  type: 'platform' | 'component' | 'workspace' | 'service' | 'file';
  path?: string;
}

export const CANONICAL_REGISTRY: Record<string, CanonicalEntity> = {
  // Platforms & Nodes
  'the-one-system': { id: 'the-one-system', name: 'The One System OS', type: 'platform' },
  'brilliantaire-os': { id: 'brilliantaire-os', name: 'Brilliantaire OS', type: 'platform' },

  // Layers & Runtimes
  'supernova': { id: 'supernova', name: 'Supernova Runtime', type: 'component', path: 'src/runtime' },
  'kernel': { id: 'kernel', name: 'Brilliantaire Execution Kernel', type: 'component', path: 'src/kernel' },
  'executive': { id: 'executive', name: 'Executive Layer', type: 'component', path: 'src/executive' },
  'intelligence': { id: 'intelligence', name: 'Operations Intelligence Layer', type: 'component', path: 'src/intelligence' },
  'knowledge': { id: 'knowledge', name: 'Grounded Intelligence Index Graph', type: 'component', path: 'src/knowledge' },
  'integrations': { id: 'integrations', name: 'Universal Integration Framework', type: 'component', path: 'src/integrations' },
  'live': { id: 'live', name: 'Live Operations Projection Layer', type: 'component', path: 'src/kernel/live' },

  // Workspaces
  'icyflamze': { id: 'icyflamze', name: 'Icyflamze Studio', type: 'workspace' },
  'profbetgeng': { id: 'profbetgeng', name: 'ProfBetGeng', type: 'workspace' },
  'treegroove': { id: 'treegroove', name: 'TreeGroove Records', type: 'workspace' },
  'joy-beauty-studio': { id: 'joy-beauty-studio', name: 'Joy Beauty Studio', type: 'workspace' },
  'avatar': { id: 'avatar', name: 'Avatar Studio', type: 'workspace' },
  'podcast': { id: 'podcast', name: 'Podcast Engine', type: 'workspace' },
  'ai-school': { id: 'ai-school', name: 'AI School', type: 'workspace' }
};

export const APPROVED_DIRECTORIES = [
  'src/kernel',
  'src/runtime',
  'src/executive',
  'src/intelligence',
  'src/knowledge',
  'src/integrations',
  'src/workspaces',
  'scripts',
  'config',
  'dashboard',
  'docs',
  'memory',
  'Backend Services',
  'Brilliantier_Catalogue',
  'CLAUDE_FOLLOW_UP_EVIDENCE',
  'CLAUDE_REVIEW_PACKAGE',
  'Developer',
  'EVIDENCE_FRAMEWORK_VALIDATION',
  'Google Drive',
  'Knowledge Core',
  'LTX-Video',
  'Landing Page Factory',
  'Landing Page Sites',
  'OneSystem_CommandCenter',
  'Projects',
  'Public',
  'Sovereign_Intelligence',
  'Supernova_System',
  'TreeGrooveProjects',
  '__pycache__',
  'agentos_client',
  'ai-engineering-hub',
  'anti-slop-llm',
  'antigravity',
  'antigravity_systems',
  'audit_watchdog',
  'autoskills',
  'bin',
  'brilliantaire-briefs',
  'cadence_analyzer',
  'campaign_ledger',
  'claude-code-best-practice',
  'codex-workspace',
  'components',
  'coverage',
  'data',
  'edge-logic',
  'evidence',
  'go',
  'graphmind',
  'harness-test-v1',
  'hooks',
  'icyflamze-ai-studio',
  'images',
  'inputAudio',
  'inputs',
  'lfs',
  'lib',
  'logs',
  'mic_dispatcher',
  'models',
  'nltk_data',
  'novalocal',
  'nvidia_tools',
  'obsidian_graph',
  'one-system',
  'outputs',
  'project',
  'recordings',
  'render-mcp-server',
  'repo-sentinel',
  'reports',
  'scratch',
  'sentinel-os',
  'siyuan',
  'siyuan-repo',
  'skills',
  'social-media-agent-kit',
  'sounds',
  'staging',
  'supernova',
  'supernova_design_system',
  'supernova_memory_vault',
  'supernova_tools',
  'supernova_workspace',
  'system',
  'telemetry',
  'templates',
  'test_inputs',
  'tools',
  'venv_stable',
  'voice_input',
  'voice_queue',
  'voice_sessions',
  'voice_vibe_asr',
  'workflows',
  'workspaces',
];

export const DEPRECATED_COMPONENTS = [
  'sentinel-os'
];

export const CANONICAL_EVENTS = [
  'governance:audit-started',
  'governance:drift-detected',
  'governance:audit-completed'
];
