export interface CommandDefinition {
  name: string;
  aliases: string[];
  description: string;
  npmScript: string;
  owningAgent: string;
  riskLevel: 'low' | 'medium' | 'high';
  outputType: string;
  enabled: boolean;
  requiresExactName: boolean;
}

export const COMMAND_REGISTRY: CommandDefinition[] = [
  {
    name: 'audit',
    aliases: ['check', 'verify'],
    description: 'Verify workspace structure, files, and local skills health',
    npmScript: 'audit',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'brief',
    aliases: ['report', 'summary'],
    description: 'Compile and print a clean operational summary brief',
    npmScript: 'brief',
    owningAgent: 'OS Architect',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'next',
    aliases: ['actions', 'next-actions'],
    description: 'List ranked next actions grouped by category',
    npmScript: 'next',
    owningAgent: 'Action Router',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'agents',
    aliases: ['council', 'roster'],
    description: 'Display active productivity agents council details',
    npmScript: 'agents',
    owningAgent: 'OS Architect',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'ingest',
    aliases: ['scan-notes', 'obsidian'],
    description: 'Recursively scan markdown notes from active vaults (Read-Only)',
    npmScript: 'ingest',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'daily-brief',
    aliases: ['daily', 'today'],
    description: 'Generate daily brief operations report output file',
    npmScript: 'daily-brief',
    owningAgent: 'Action Router',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'sync-status',
    aliases: ['sync'],
    description: 'Back up and sync vault snapshot to repository status lists',
    npmScript: 'sync-status',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'stage-write',
    aliases: ['stage', 'prepare-write'],
    description: 'Stage markdown status reports to outputs/write_staging/',
    npmScript: 'stage-write',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'approve-write',
    aliases: ['approve', 'write-to-vault'],
    description: 'Approve and execute safe write back into the active Obsidian vault (High Risk)',
    npmScript: 'approve-write',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'high',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'write-log',
    aliases: ['logs', 'write-history'],
    description: 'Read and display recent write history timeline logs',
    npmScript: 'write-log',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'build',
    aliases: ['compile'],
    description: 'Compile TypeScript source files to JavaScript dist/',
    npmScript: 'build',
    owningAgent: 'Build Operator',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'campaign-help',
    aliases: ['campaign commands', 'campaigns-help'],
    description: 'Print registry of available campaign template engine tasks',
    npmScript: 'campaign-help',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'campaign',
    aliases: ['campaigns'],
    description: 'Execute campaign templates generation workflows (Medium Risk)',
    npmScript: 'campaign',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'voice-help',
    aliases: ['voice commands', 'voice-list'],
    description: 'Print registry of all allowed voice command phrases',
    npmScript: 'voice-help',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'voice-queue',
    aliases: ['voice'],
    description: 'Process text-based voice command queue inbox files safely (Medium Risk)',
    npmScript: 'voice-queue',
    owningAgent: 'Build Operator',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'voice-pending',
    aliases: ['pending voice', 'voice review'],
    description: 'List voice commands pending confirmation review',
    npmScript: 'voice-pending',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'voice-confirm',
    aliases: ['confirm voice'],
    description: 'Approve and execute a pending voice command (High Risk)',
    npmScript: 'voice-confirm',
    owningAgent: 'Build Operator',
    riskLevel: 'high',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'voice-deny',
    aliases: ['deny voice'],
    description: 'Deny and discard a pending voice command (Medium Risk)',
    npmScript: 'voice-deny',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'vibevoice-help',
    aliases: ['vibe help', 'voice bridge help'],
    description: 'Print VibeVoice transcript bridge safety menus',
    npmScript: 'vibevoice-help',
    owningAgent: 'Build Operator',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'vibevoice-transcript',
    aliases: ['transcribe voice', 'voice transcript'],
    description: 'Scan and ingest manual transcripts into queue inbox',
    npmScript: 'vibevoice-transcript',
    owningAgent: 'Build Operator',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'vibevoice-test',
    aliases: ['voice test'],
    description: 'Generate sample test files under manual voice input',
    npmScript: 'vibevoice-test',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'live-asr-help',
    aliases: ['asr help', 'microphone help'],
    description: 'Print Live ASR safety menus and command flow',
    npmScript: 'live-asr-help',
    owningAgent: 'Build Operator',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'live-asr-import',
    aliases: ['import voice', 'import asr'],
    description: 'Import raw live transcripts from voice_input/live into manual staging',
    npmScript: 'live-asr-import',
    owningAgent: 'Build Operator',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'live-asr-test',
    aliases: ['asr test', 'microphone test'],
    description: 'Generate mock ASR transcript inputs under voice_input/live',
    npmScript: 'live-asr-test',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'live-asr-record',
    aliases: ['record voice', 'microphone record'],
    description: 'Microphone recording interface info and staging parameters',
    npmScript: 'live-asr-record',
    owningAgent: 'Build Operator',
    riskLevel: 'medium',
    outputType: 'console',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'campaign-scheduler-help',
    aliases: ['scheduler help', 'posting help'],
    description: 'Print campaign scheduler available tasks and parameters',
    npmScript: 'campaign-scheduler-help',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'campaign-scheduler',
    aliases: ['scheduler', 'posting queue'],
    description: 'Run campaign scheduler draft tasks (create, queue, log, status)',
    npmScript: 'campaign-scheduler',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'campaign-simulate-help',
    aliases: ['simulation help', 'campaign validation help'],
    description: 'Print campaign simulation available tasks and parameters',
    npmScript: 'campaign-simulate-help',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'campaign-simulate',
    aliases: ['simulate campaign', 'validate campaign'],
    description: 'Run campaign simulation audits (sporty, validate sporty, status sporty)',
    npmScript: 'campaign-simulate',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'mesh-telemetry-help',
    aliases: ['telemetry help', 'mesh help'],
    description: 'Print mesh telemetry available tasks and parameters',
    npmScript: 'mesh-telemetry-help',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'mesh-telemetry',
    aliases: ['telemetry', 'mesh'],
    description: 'Run system mesh telemetry logging (snapshot, report, campaign sporty, status)',
    npmScript: 'mesh-telemetry',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'dashboard-export',
    aliases: ['export dashboard', 'dashboard data'],
    description: 'Export system statuses and log metrics to public/dashboard-data.json',
    npmScript: 'dashboard:export',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'dashboard-build',
    aliases: ['build dashboard'],
    description: 'Compile the Vite dashboard production build',
    npmScript: 'dashboard:build',
    owningAgent: 'Build Operator',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'automation-help',
    aliases: ['automation list', 'routine help'],
    description: 'Print registry of pre-approved local automation routines',
    npmScript: 'automation-help',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'automation-runner',
    aliases: ['run automation', 'routine'],
    description: 'Execute a pre-approved local automation routine (Medium Risk)',
    npmScript: 'automation-runner',
    owningAgent: 'Build Operator',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'background-help',
    aliases: ['background automation help', 'background help'],
    description: 'Print registry of pre-approved controlled background automation schedules',
    npmScript: 'background-help',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'background-dry-run',
    aliases: ['background test', 'schedule dry run'],
    description: 'Simulate the execution of a background automation schedule',
    npmScript: 'background-dry-run',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'background-status',
    aliases: ['background status', 'schedule status'],
    description: 'Check active configurations and diagnostic statuses of background schedules',
    npmScript: 'background-status',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'background-run',
    aliases: ['run background', 'schedule run'],
    description: 'Execute a pre-approved background schedule routine (High Risk)',
    npmScript: 'background-run',
    owningAgent: 'Build Operator',
    riskLevel: 'high',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'platform-adapter-help',
    aliases: ['platform help', 'posting package help'],
    description: 'Print platform output adapters safety manuals',
    npmScript: 'platform-adapter-help',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'platform-adapter',
    aliases: ['platform package', 'posting package'],
    description: 'Generate manual platform posting packages (Medium Risk)',
    npmScript: 'platform-adapter',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'platform-verify-help',
    aliases: ['platform verification help', 'verify package help'],
    description: 'Print platform verification gates safety manuals',
    npmScript: 'platform-verify-help',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'platform-verify',
    aliases: ['verify platform', 'verify package'],
    description: 'Verify generated platform packages (Medium Risk)',
    npmScript: 'platform-verify',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'manual-release-help',
    aliases: ['release help', 'manual posting help'],
    description: 'Print manual release safety manuals',
    npmScript: 'manual-release-help',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'manual-release',
    aliases: ['release', 'manual posting'],
    description: 'Generate manual release checklists and runbooks (Medium Risk)',
    npmScript: 'manual-release',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'distribution-metrics-help',
    aliases: ['metrics help', 'distribution help'],
    description: 'Print manual distribution metrics safety manuals',
    npmScript: 'distribution-metrics-help',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'distribution-metrics',
    aliases: ['metrics', 'distribution'],
    description: 'Generate manual distribution metrics entry files, reports, and indexes (Medium Risk)',
    npmScript: 'distribution-metrics',
    owningAgent: 'Creative Revenue Strategist',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'knowledge-harvest-help',
    aliases: ['learning help', 'harvest help'],
    description: 'Print commands for Knowledge Harvest Engine',
    npmScript: 'knowledge-harvest-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'knowledge-harvest',
    aliases: ['learn', 'harvest'],
    description: 'Execute Knowledge Harvest Engine commands (Medium Risk)',
    npmScript: 'knowledge-harvest',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-bridge-help',
    aliases: ['notebook help', 'notebooklm help'],
    description: 'Print commands for NotebookLM MCP Sidecar Bridge',
    npmScript: 'notebooklm-bridge-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-bridge',
    aliases: ['notebooklm', 'notebook bridge'],
    description: 'Execute NotebookLM MCP Sidecar Bridge tasks (Medium Risk)',
    npmScript: 'notebooklm-bridge',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-detect-help',
    aliases: ['notebook mcp help', 'mcp notebook help'],
    description: 'Print commands for NotebookLM MCP Adapter Detection',
    npmScript: 'notebooklm-mcp-detect-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-detect',
    aliases: ['notebook mcp detect', 'notebooklm mcp'],
    description: 'Execute NotebookLM MCP Adapter Detection scans (Medium Risk)',
    npmScript: 'notebooklm-mcp-detect',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-execute-help',
    aliases: ['notebook execution help', 'mcp execution help'],
    description: 'Print commands for NotebookLM MCP Dry-Run Execution',
    npmScript: 'notebooklm-mcp-execute-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-execute',
    aliases: ['notebook execute', 'mcp execute'],
    description: 'Execute NotebookLM MCP Adapter Dry-Run simulations (Medium Risk)',
    npmScript: 'notebooklm-mcp-execute',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-auth-help',
    aliases: ['notebook auth help', 'mcp auth help'],
    description: 'Print commands for NotebookLM MCP Live Authorization Validation',
    npmScript: 'notebooklm-mcp-auth-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-auth',
    aliases: ['notebook auth', 'mcp auth'],
    description: 'Execute NotebookLM MCP Live Authorization Validation checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-auth',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-harden-help',
    aliases: ['notebook hardening help', 'mcp hardening help'],
    description: 'Print commands for NotebookLM MCP Connector Hardening',
    npmScript: 'notebooklm-mcp-harden-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-harden',
    aliases: ['notebook harden', 'mcp harden'],
    description: 'Execute NotebookLM MCP Connector Hardening checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-harden',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-setup-guide-help',
    aliases: ['notebook setup help', 'mcp setup help'],
    description: 'Print commands for NotebookLM MCP Manual Setup Instructions',
    npmScript: 'notebooklm-mcp-setup-guide-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-setup-guide',
    aliases: ['notebook setup', 'mcp setup'],
    description: 'Execute NotebookLM MCP Manual Setup Instructions checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-setup-guide',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-readiness-gate-help',
    aliases: ['notebook readiness help', 'mcp readiness help'],
    description: 'Print commands for NotebookLM MCP Setup Review and Readiness Gate',
    npmScript: 'notebooklm-mcp-readiness-gate-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-readiness-gate',
    aliases: ['notebook readiness', 'mcp readiness'],
    description: 'Execute NotebookLM MCP Setup Review and Readiness Gate checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-readiness-gate',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-correction-pack-help',
    aliases: ['notebook correction help', 'mcp correction help'],
    description: 'Print commands for NotebookLM MCP Local Setup Correction Pack',
    npmScript: 'notebooklm-mcp-correction-pack-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-correction-pack',
    aliases: ['notebook correction', 'mcp correction'],
    description: 'Execute NotebookLM MCP Local Setup Correction Pack checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-correction-pack',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-completion-review-help',
    aliases: ['notebook completion help', 'mcp completion help'],
    description: 'Print commands for NotebookLM MCP Manual Setup Completion Review',
    npmScript: 'notebooklm-mcp-completion-review-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-completion-review',
    aliases: ['notebook completion', 'mcp completion'],
    description: 'Execute NotebookLM MCP Manual Setup Completion Review checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-completion-review',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-secrets-help',
    aliases: ['notebook secrets help', 'mcp secrets help'],
    description: 'Print commands for NotebookLM MCP Local Secrets Staging Guide',
    npmScript: 'notebooklm-mcp-secrets-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-secrets',
    aliases: ['notebook secrets', 'mcp secrets'],
    description: 'Execute NotebookLM MCP Local Secrets Staging Guide checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-secrets',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-fix-cycle-help',
    aliases: ['notebook fix help', 'mcp fix help'],
    description: 'Print commands for NotebookLM MCP Setup Fix Cycle',
    npmScript: 'notebooklm-mcp-fix-cycle-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-fix-cycle',
    aliases: ['notebook fix', 'mcp fix'],
    description: 'Execute NotebookLM MCP Setup Fix Cycle checks (Medium Risk)',
    npmScript: 'notebooklm-mcp-fix-cycle',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-mcp-live-help',
    aliases: ['notebook live help', 'mcp live help'],
    description: 'Print commands for NotebookLM MCP Live Adapter Integration',
    npmScript: 'notebooklm-mcp-live-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-mcp-live',
    aliases: ['notebook live', 'mcp live'],
    description: 'Execute NotebookLM MCP Live Adapter Integration checks (High Risk)',
    npmScript: 'notebooklm-mcp-live',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'high',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'notebooklm-response-intelligence-help',
    aliases: ['response intelligence help', 'notebook intelligence help'],
    description: 'Print help menu for NotebookLM response intelligence processor',
    npmScript: 'notebooklm-response-intelligence-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'notebooklm-response-intelligence',
    aliases: ['response intelligence', 'notebook intelligence'],
    description: 'Process NotebookLM responses into structured intelligence files',
    npmScript: 'notebooklm-response-intelligence',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'list-schedules',
    aliases: ['schedules', 'list schedules'],
    description: 'List registered background schedules',
    npmScript: 'list-schedules',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'scheduler-health',
    aliases: ['scheduler health', 'health status'],
    description: 'Print background scheduler health status analytics',
    npmScript: 'scheduler-health',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'scheduler-report',
    aliases: ['scheduler report', 'compile report'],
    description: 'Generate daily and weekly scheduler performance reports',
    npmScript: 'scheduler-report',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-sources',
    aliases: ['narrator source scan', 'narrator scan'],
    description: 'Scan approved sources and generate narrator source snapshot',
    npmScript: 'narrator-sources',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-validate',
    aliases: ['validate narrator', 'narrator check'],
    description: 'Validate narrator_card.json output structure and safety',
    npmScript: 'narrator-validate',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-brief-help',
    aliases: ['narrator brief help', 'brief composer help'],
    description: 'Print help commands for the narrator brief composer',
    npmScript: 'narrator-brief-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-brief',
    aliases: ['narrator brief', 'compose narrator'],
    description: 'Compile target-specific operational briefs from system telemetry',
    npmScript: 'narrator-brief',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-live-feed-help',
    aliases: ['live narrator help', 'narrator feed help'],
    description: 'Print help commands for the narrator live feed controller',
    npmScript: 'narrator-live-feed-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-live-feed',
    aliases: ['narrator feed', 'live narrator'],
    description: 'Compile and check read-only live dashboard feeds and event logs',
    npmScript: 'narrator-live-feed',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-feed-watch',
    aliases: ['watch narrator', 'narrator watcher'],
    description: 'Run the local read-only file watcher daemon for narrator feed updates',
    npmScript: 'narrator-feed-watch',
    owningAgent: 'Workflow Auditor',
    riskLevel: 'medium',
    outputType: 'console',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'narrator-voice-sync-help',
    aliases: ['narrator voice help', 'voice sync help'],
    description: 'Print help commands for the narrator voice sync controller',
    npmScript: 'narrator-voice-sync-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-voice-sync',
    aliases: ['narrator voice', 'sync narrator voice'],
    description: 'Compile voice-ready packets and stage manual VNP voice queue entries',
    npmScript: 'narrator-voice-sync',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'files',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-tts-queue-help',
    aliases: ['tts queue help', 'narrator tts help'],
    description: 'Print help commands for the narrator tts queue controller',
    npmScript: 'narrator-tts-queue-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-tts-queue',
    aliases: ['narrator tts', 'tts queue'],
    description: 'Stage and manage local offline text-to-speech rendering requests',
    npmScript: 'narrator-tts-queue',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'narrator-tts-renderer-help',
    aliases: ['tts renderer help', 'narrator tts renderer help'],
    description: 'Print help commands for the narrator tts renderer controller',
    npmScript: 'narrator-tts-renderer-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-tts-renderer',
    aliases: ['narrator tts renderer', 'tts renderer'],
    description: 'Dry-run and compile approved text-to-speech requests to offline audio',
    npmScript: 'narrator-tts-renderer',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  },
  {
    name: 'narrator-tts-models-help',
    aliases: ['tts models help', 'narrator tts models help'],
    description: 'Print help commands for the narrator tts model and cache manager',
    npmScript: 'narrator-tts-models-help',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'low',
    outputType: 'console',
    enabled: true,
    requiresExactName: false
  },
  {
    name: 'narrator-tts-models',
    aliases: ['narrator tts models', 'tts models'],
    description: 'Register, verify, and clean up offline speech synthesis assets and cache',
    npmScript: 'narrator-tts-models',
    owningAgent: 'Knowledge Librarian',
    riskLevel: 'medium',
    outputType: 'files',
    enabled: true,
    requiresExactName: true
  }
];


