console.log("=========================================");
console.log("🚦 ASR VALIDATION CHAIN EXECUTION REPORT HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-validation-chain-execution-report\"");
console.log("   or: npm run command -- \"asr-validation-chain-execution-report-help\"");
console.log("");
console.log("Primary Objective:");
console.log("  Validates and compiles a report showing whether the system reaches dry_run_ready");
console.log("  without enabling transcription by running or reading outputs from the full ASR validation chain.");
console.log("");
console.log("Required Validation Chain Gates:");
console.log("  1. asr-human-staged-asset-verification-pass");
console.log("  2. asr-manual-asset-presence-preflight");
console.log("  3. asr-checksum-manifest-validation-gate");
console.log("  4. asr-audio-input-staging-validation-gate");
console.log("  5. asr-readiness-join-gate");
console.log("  6. asr-manual-asset-revalidation-pass");
console.log("  7. asr-gate-rerun-orchestrator");
console.log("");
console.log("Generated Outputs (under outputs/asr_validation_chain/):");
console.log("  - asr_validation_chain_report_2026-06-01.md       (Master report)");
console.log("  - asr_validation_chain_preconditions_2026-06-01.md (Preconditions report)");
console.log("  - asr_validation_chain_step_results_2026-06-01.md  (Tabular gate step results)");
console.log("  - asr_validation_chain_blockers_2026-06-01.md      (Unresolved gate blockers)");
console.log("  - asr_validation_chain_final_status_2026-06-01.md  (Consolidated final status)");
console.log("  - asr_validation_chain_safety_2026-06-01.md        (Safety verification checklists)");
console.log("  - asr_validation_chain_summary_2026-06-01.md       (Operational summary report)");
console.log("  - asr_next_actions_2026-06-01.md                   (Roadmap progression)");
console.log("  - asr_validation_chain_manifest_2026-06-01.json    (Unified output JSON manifest)");
console.log("");
console.log("Safety Limits Enforced:");
console.log("  - ASR Execution: false");
console.log("  - Audio Transcription: false");
console.log("  - External API calls: false");
console.log("  - Model downloads: false");
console.log("  - Mutate model files: false");
console.log("  - Mutate audio files: false");
console.log("");
console.log("Risk Level: LOW (Read-Only Gate Checker)");
console.log("=========================================");
