console.log("=========================================");
console.log("🔍 ASR MANUAL ASSET REVALIDATION PASS HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-manual-asset-revalidation-pass\"");
console.log("");
console.log("This pass aggregates and consolidates status outputs from prior ASR validation");
console.log("gates (manifest checksum, audio staging, readiness join, and preflight checks).");
console.log("It determines whether the system is fully prepared to enter dry-run offline");
console.log("transcription state.");
console.log("");
console.log("Execution constraints enforced in this pass:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Consolidates manifests from:");
console.log("  - outputs/asr_validation/asr_checksum_validation_manifest_2026-06-01.json");
console.log("  - outputs/asr_audio_staging/asr_audio_staging_manifest_2026-06-01.json");
console.log("  - outputs/asr_readiness_join/asr_readiness_join_manifest_2026-06-01.json");
console.log("  - outputs/asr_asset_preflight/asr_asset_preflight_manifest_2026-06-01.json");
console.log("");
console.log("Pipes to target output location: outputs/asr_revalidation/");
console.log("=========================================");
