console.log("=========================================");
console.log("🎛️ ASR OFFLINE EXECUTION APPROVAL SWITCH HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-offline-execution-approval-switch\"");
console.log("");
console.log("This command establishes the human-controlled approval switch that");
console.log("authorizes selected dry-run-ready local audio files for future offline ASR");
console.log("transcription, while keeping actual ASR execution disabled by default.");
console.log("");
console.log("Available Actions:");
console.log("  - Read the latest validation chain manifest outputs.");
console.log("  - Read staged eligible audio candidate listings.");
console.log("  - Map candidate parameters to default locked switches.");
console.log("  - Generate human operator checklists, approval manifests, and lock logs.");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_execution_approval/");
console.log("=========================================");
