console.log("=========================================");
console.log("🚦 ASR GATE RERUN ORCHESTRATOR HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-gate-rerun-orchestrator\"");
console.log("   or: npm run command -- \"asr-gate-rerun-orchestrator-help\"");
console.log("");
console.log("Primary Objective:");
console.log("  Evaluates the offline ASR readiness gate sequence after human staged assets verification.");
console.log("");
console.log("Required Gate Sequence:");
console.log("  1. asr-manual-asset-presence-preflight");
console.log("  2. asr-checksum-manifest-validation-gate");
console.log("  3. asr-audio-input-staging-validation-gate");
console.log("  4. asr-readiness-join-gate");
console.log("  5. asr-manual-asset-revalidation-pass");
console.log("");
console.log("Safety Restrictions:");
console.log("  - ASR called: false (Whisper execution is completely blocked)");
console.log("  - Transcription generated: false (No audio translation/transcription is performed)");
console.log("  - External APIs: false (External network traffic is strictly disabled)");
console.log("  - Downloads: false (No automated model downloading)");
console.log("");
console.log("Safety Rule:");
console.log("  If human staged asset verification is not 'ready_for_gate_rerun', the orchestrator will");
console.log("  fail closed, skip running the gate sequence, and produce blocker reports only.");
console.log("=========================================");
