console.log("=========================================");
console.log("🎙️ OFFLINE ASR MODEL ACQUISITION & CHECKSUM GATE");
console.log("=========================================");
console.log("");
console.log("Usage: npm run asr-model-gate -- <command> [options]");
console.log("");
console.log("Available commands:");
console.log("  help                                 Print this help guide");
console.log("  guide                                Generate ASR model manual placement and acquisition guide");
console.log("  inventory                            Scan models/asr/whisper/ directory for file inventory");
console.log("  checksum                             Audit staged Whisper model hashes using Node crypto");
console.log("  readiness                            Evaluate model readiness gates and system safety validations");
console.log("  status                               Print ASR model gate capabilities and latest reports status");
console.log("");
console.log("Example runs:");
console.log("  npm run asr-model-gate -- \"help\"");
console.log("  npm run asr-model-gate -- \"guide\"");
console.log("  npm run asr-model-gate -- \"inventory\"");
console.log("  npm run asr-model-gate -- \"checksum\"");
console.log("  npm run asr-model-gate -- \"readiness\"");
console.log("  npm run asr-model-gate -- \"status\"");
console.log("=========================================");
