console.log("=========================================");
console.log("🛠️ ASR MANUAL ASSET STAGING OPERATOR PACKET GENERATOR HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-manual-asset-staging-operator-packet\"");
console.log("   or: npm run command -- \"asr-manual-asset-staging-operator-packet-help\"");
console.log("");
console.log("Primary Objective:");
console.log("  Generates a human operator staging guide packet with capture commands, manifest update");
console.log("  rules, approved audio paths, and the post-staging verification gate sequence.");
console.log("");
console.log("Generated Outputs (under outputs/asr_operator_packet/):");
console.log("  - asr_operator_packet_2026-06-01.md                 (Combined guide document)");
console.log("  - asr_model_placement_commands_2026-06-01.md        (Commands for model verify)");
console.log("  - asr_sha256_capture_2026-06-01.md                  (macOS/Linux hash utility commands)");
console.log("  - asr_file_size_capture_2026-06-01.md               (macOS/Linux size utility commands)");
console.log("  - asr_manifest_update_guide_2026-06-01.md           (Required JSON fields configuration)");
console.log("  - asr_audio_placement_guide_2026-06-01.md           (Staging folder location rules)");
console.log("  - asr_post_staging_rerun_guide_2026-06-01.md        (Post-staging gate sequence commands)");
console.log("  - asr_phase_12a_lock_reminder_2026-06-01.md         (Safety locks warning)");
console.log("  - asr_next_actions_2026-06-01.md                    (Next actions roadmap)");
console.log("  - asr_operator_packet_manifest_2026-06-01.json      (Staging metadata audit ledger)");
console.log("");
console.log("Safety Restrictions:");
console.log("  - ASR called: false");
console.log("  - Transcription generated: false");
console.log("  - External API called: false");
console.log("  - Download allowed: false");
console.log("");
console.log("Risk Level: MEDIUM");
console.log("=========================================");
