console.log("=========================================");
console.log("🎙️ ASR AUDIO INPUT STAGING VALIDATION GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-audio-input-staging-validation-gate\"");
console.log("");
console.log("This gate audits local staged audio files in recordings/, inputAudio/, outputs/asr_inputs/");
console.log("validating file extensions, size constraints, path boundary safety, and mapping");
console.log("route previews without executing models or transcribing speech.");
console.log("");
console.log("Available Actions (automated during validation):");
console.log("  - Scan approved input directories for eligible speech files (.wav, .mp3, .m4a, .flac, .ogg)");
console.log("  - Filter files based on extension, non-empty size, traversal checks, and executables");
console.log("  - Inspect model validation gate trust logs from Phase 11Z-C");
console.log("  - Generate mock route preview tables mapping eligible audios");
console.log("  - Compile staging summaries, eligible file logs, and action roadmaps");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_audio_staging/");
console.log("=========================================");
