console.log("=========================================");
console.log("🎙️ ASR CHECKSUM MANIFEST VALIDATION GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-checksum-manifest-validation-gate\"");
console.log("");
console.log("This gate validates root and official asr-checksum-manifest.json configurations");
console.log("against local model files, calculating SHA256 hashes to verify model safety.");
console.log("");
console.log("Available Actions (automated during validation):");
console.log("  - Read and cross-compare root and official narrator asr-checksum-manifest.json files");
console.log("  - Validate all manifest fields (model_filename,expected_sha256,trust_status,etc.)");
console.log("  - Scan models/asr/whisper/ directory for matching binary files");
console.log("  - Calculate local SHA256 checksums to verify integrity match");
console.log("  - Compare file size requirements");
console.log("  - Compile validation reports, checksum mismatch logs, and roadmap roadmaps");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No models run)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_validation/");
console.log("=========================================");
