console.log("=========================================");
console.log("🎙️ OFFLINE ASR DRY-RUN TRANSCRIPTION GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-dry-run-transcription-gate\"");
console.log("");
console.log("This gate evaluates system readiness for local Whisper offline transcription");
console.log("without executing models or transcribing audio waveforms.");
console.log("");
console.log("Available Actions (automated during gate check):");
console.log("  - Scan ASR local models inventory under models/asr/whisper/");
console.log("  - Audit model file sizes, allowed extensions, and SHA256 integrity");
console.log("  - Scan approved input directories for eligible staged audio assets");
console.log("  - Generate mock route mapping configurations for future execution");
console.log("  - Output dry-run summary reports and verification manifests");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No models loaded)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text run)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No network telemetry)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (Manual model placement only)");
console.log("");
console.log("Pipes to target output location: outputs/asr_dry_run/");
console.log("=========================================");
