console.log("=========================================");
console.log("🎛️ ASR OFFLINE HUMAN SELECTION PACKET HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run asr-offline-human-approval-selection-packet -- --audio-id=<id> --model-id=<id> [options]");
console.log("");
console.log("This command compiles the human operator selection packet, authorizing");
console.log("one validated audio candidate and one verified local Whisper model for a future");
console.log("offline transcription run, while keeping final transcription disabled by default.");
console.log("");
console.log("Required Arguments:");
console.log("  --audio-id=<id>        The unique identifier of the validated audio candidate.");
console.log("  --model-id=<id>        The unique identifier of the verified Whisper model (e.g., model_001).");
console.log("");
console.log("Options:");
console.log("  --date=<YYYY-MM-DD>    The date of the selection run (default: 2026-06-01).");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_human_selection/");
console.log("=========================================");
