console.log("=========================================");
console.log("🚦 ASR OPERATOR PACKET COMPLETION AUDIT HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-operator-packet-completion-audit\"");
console.log("   or: npm run command -- \"asr-operator-packet-completion-audit-help\"");
console.log("");
console.log("Primary Objective:");
console.log("  Audits whether the human operator has completed the manual staging rules from Phase 11Z-K");
console.log("  by staging model binaries, manifests update checklist, and approved audio files.");
console.log("");
console.log("Generated Outputs (under outputs/asr_operator_completion_audit/):");
console.log("  - asr_operator_completion_audit_2026-06-01.md                 (Combined audit document)");
console.log("  - asr_operator_model_placement_audit_2026-06-01.md            (Whisper binaries placement audit)");
console.log("  - asr_operator_manifest_completion_audit_2026-06-01.md        (JSON properties check results)");
console.log("  - asr_operator_audio_staging_audit_2026-06-01.md              (Audio staging directory check results)");
console.log("  - asr_operator_rerun_readiness_2026-06-01.md                  (Verify gate rerun sequence commands)");
console.log("  - asr_operator_blockers_2026-06-01.md                         (Staging deficiency blockers checklists)");
console.log("  - asr_operator_summary_2026-06-01.md                          (Audit summary rollup)");
console.log("  - asr_next_actions_2026-06-01.md                              (Next actions roadmap)");
console.log("  - asr_operator_completion_audit_manifest_2026-06-01.json      (Staging checklist metrics ledger)");
console.log("");
console.log("Safety Restrictions:");
console.log("  - ASR called: false");
console.log("  - Transcription generated: false");
console.log("  - External API called: false");
console.log("  - Download allowed: false");
console.log("");
console.log("Risk Level: MEDIUM");
console.log("=========================================");
