console.log("=========================================");
console.log("🔗 ASR READINESS JOIN GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-readiness-join-gate\"");
console.log("");
console.log("This gate integrates the model checksum validation signals (Phase 11Z-C) and");
console.log("audio input staging validation signals (Phase 11Z-D) into a unified");
console.log("ASR readiness manifest under strict offline-first safety rules.");
console.log("");
console.log("Available Actions (automated during validation):");
console.log("  - Read cryptographic model checksum manifests and summaries.");
console.log("  - Read local audio input staging manifests and summaries.");
console.log("  - Join signals, perform final readiness evaluations, and map route eligibility.");
console.log("  - Compile integrated checklists of active blockers preventing ASR dry-run status.");
console.log("  - Generate combined manifest and detail reports.");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_readiness_join/");
console.log("=========================================");
