console.log("=========================================");
console.log("📋 ASR MANUAL ASSET INTAKE CHECKLIST HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-manual-asset-intake-checklist\"");
console.log("");
console.log("This utility generates human checklists and guides for manually placing Whisper");
console.log("models and staging audio files before running validation rerun sequences.");
console.log("");
console.log("Available Actions (automated during checklist compilation):");
console.log("  - Generate model placement checklist highlighting destinations.");
console.log("  - Generate manifest update instructions detailing configuration constraint rules.");
console.log("  - Generate audio staging guidelines with formats and safety filters.");
console.log("  - Output exact gate validation rerun script sequences.");
console.log("  - Compile blocker resolution roadmaps and safety reminder documents.");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_manual_intake/");
console.log("=========================================");
