console.log("=========================================");
console.log("🎙️ OFFLINE ASR MODEL ACQUISITION & CHECKSUM GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run asr-model-gate -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help         Print this help guide");
console.log("  guide        Generate manual Whisper ASR model acquisition guide");
console.log("  inventory    Inspect models/asr/whisper/ and build file details inventory");
console.log("  checksum     Calculate cryptographically secure SHA256 hashes of models and check integrity");
console.log("  readiness    Evaluate staged audio, inventory models, review hashes, and check manual enable flags");
console.log("  status       Print dashboard summarizing all generated guides, checklists, and blocker audits");
console.log("");
console.log("Example runs:");
console.log("  npm run asr-model-gate -- \"help\"");
console.log("  npm run asr-model-gate -- \"guide\"");
console.log("  npm run asr-model-gate -- \"inventory\"");
console.log("  npm run asr-model-gate -- \"checksum\"");
console.log("  npm run asr-model-gate -- \"readiness\"");
console.log("  npm run asr-model-gate -- \"status\"");
console.log("=========================================");
