console.log("=========================================");
console.log("🚦 ASR VERIFICATION RERUN TRIGGER PACKET HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-verification-rerun-trigger-packet\"");
console.log("   or: npm run command -- \"asr-verification-rerun-trigger-packet-help\"");
console.log("");
console.log("Primary Objective:");
console.log("  Generates the final local-first rerun trigger packet for the full ASR validation chain");
console.log("  after operator packet completion has been confirmed.");
console.log("");
console.log("Generated Outputs (under outputs/asr_rerun_trigger/):");
console.log("  - asr_verification_rerun_trigger_packet_2026-06-01.md      (Master trigger packet report)");
console.log("  - asr_rerun_preconditions_2026-06-01.md                   (Preconditions status checklist)");
console.log("  - asr_rerun_command_sequence_2026-06-01.md                 (Rerun validation sequence commands)");
console.log("  - asr_rerun_blockers_2026-06-01.md                         (Unresolved prerequisites checklists)");
console.log("  - asr_rerun_safety_lock_2026-06-01.md                      (Enforced safety constraints)");
console.log("  - asr_rerun_expected_outcomes_2026-06-01.md                (Post-validation target values)");
console.log("  - asr_rerun_summary_2026-06-01.md                          (Trigger process summary)");
console.log("  - asr_next_actions_2026-06-01.md                          (Roadmap progression recommendation)");
console.log("  - asr_verification_rerun_trigger_manifest_2026-06-01.json  (Rollup trigger metrics ledger)");
console.log("");
console.log("Safety Rules:");
console.log("  - ASR called: false");
console.log("  - Transcription generated: false");
console.log("  - External API called: false");
console.log("  - Download allowed: false");
console.log("  - Phase 12A lock status: LOCKED");
console.log("");
console.log("Risk Level: MEDIUM");
console.log("=========================================");
