console.log("=========================================");
console.log("🔍 ASR HUMAN-STAGED ASSET VERIFICATION PASS HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-human-staged-asset-verification-pass\"");
console.log("");
console.log("This command cross-validates manual Whisper model binary staging, checksum");
console.log("manifest registers, and eligible audio inputs against expected configurations.");
console.log("");
console.log("Staging inputs verified:");
console.log("  - Models: models/asr/whisper/ (ggml-base.en.bin, ggml-tiny.bin)");
console.log("  - Checksum Manifests: root and narrator subdirectory copies");
console.log("  - Audio Inputs: recordings/, inputAudio/, and outputs/asr_inputs/");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Output reports staged under: outputs/asr_human_staged_verification/");
console.log("=========================================");
