console.log("=========================================");
console.log("🎙️ LOCAL OFFLINE ASR ORCHESTRATOR HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run asr-orchestrator -- <command> [options]");
console.log("");
console.log("Available commands:");
console.log("  help                                 Print this help guide");
console.log("  readiness                            Validate ASR readiness, models, audio staging, and environment flags");
console.log("  create-job                           Prepare job packets for queued audio files");
console.log("  dry-run                              Simulate ASR command execution without calling shell or models");
console.log("  stage-transcript                     Create staging record and transcript placeholders");
console.log("  status                               Print ASR orchestrator capabilities and latest reports status");
console.log("");
console.log("Example runs:");
console.log("  npm run asr-orchestrator -- \"help\"");
console.log("  npm run asr-orchestrator -- \"readiness\"");
console.log("  npm run asr-orchestrator -- \"create-job\"");
console.log("  npm run asr-orchestrator -- \"dry-run\"");
console.log("  npm run asr-orchestrator -- \"stage-transcript\"");
console.log("  npm run asr-orchestrator -- \"status\"");
console.log("=========================================");
