console.log("=========================================");
console.log("🎙️ OFFLINE ASR DRY-RUN TRANSCRIPTION GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-dry-run-transcription-gate\"");
console.log("");
console.log("Description:");
console.log("  Performs a complete local dry-run audit of Whisper models checksum validation,");
console.log("  approved audio inputs inspection, and simulated routing map estimation.");
console.log("");
console.log("Operational Safety Rules:");
console.log("  - This command never calls ASR or loads neural network weights.");
console.log("  - This command never writes or alters local audio recordings or Whisper model files.");
console.log("  - This command never communicates with any external APIs or downloads online dependencies.");
console.log("  - If any configuration changes breach safety criteria, the gate immediately terminates and fails closed.");
console.log("");
console.log("Guidance:");
console.log("  - Place standard Whisper models (e.g. ggml-base.bin) in models/asr/whisper/");
console.log("  - Place eligible audio files (.wav, .mp3, etc.) inside approved folders:");
console.log("    * outputs/narrator/voice_sessions/recordings/");
console.log("    * outputs/narrator/asr/input_audio/");
console.log("  - Run the gate command exactly as shown. Aliases are forbidden by design.");
console.log("");
console.log("Example:");
console.log("  npm run command -- \"asr-dry-run-transcription-gate\"");
console.log("");
console.log("Help Command:");
console.log("  npm run command -- \"asr-dry-run-transcription-gate-help\"");
console.log("=========================================");
