console.log("=========================================");
console.log("🔍 ASR MANUAL ASSET PRESENCE PREFLIGHT HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run command -- \"asr-manual-asset-presence-preflight\"");
console.log("");
console.log("This preflight gate audits the offline ASR directories to check if required model");
console.log("binaries exist and at least one approved local audio file is present.");
console.log("");
console.log("Available Actions (automated during preflight):");
console.log("  - Check existence and read permissions of Whisper binaries under models/asr/whisper/.");
console.log("  - Check checksum manifests for schema properties and expected model entries.");
console.log("  - Audit approved folders for staged audios, accepted extensions, and size constraints.");
console.log("  - Compile blocker checklists and summary documents.");
console.log("");
console.log("Execution constraints enforced in this phase:");
console.log("  - ALLOW_ASR_EXECUTION = false        (No speech transcription)");
console.log("  - ALLOW_AUDIO_TRANSCRIPTION = false  (No speech-to-text done)");
console.log("  - ALLOW_EXTERNAL_API_CALLS = false   (No external network HTTP calls)");
console.log("  - ALLOW_MODEL_DOWNLOAD = false       (No downloads spawned)");
console.log("");
console.log("Pipes to target output location: outputs/asr_asset_preflight/");
console.log("=========================================");
