console.log("=========================================");
console.log("OFFLINE AUDIO DROP VERIFICATION & CLEANUP HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run audio-drop-verification -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help              Print this help guide");
console.log("  inventory         Scan dropped recordings and inventory size/formats");
console.log("  match-sessions    Match physical audio drops to session metadata files");
console.log("  quarantine-check  Identify unsupported or oversized files and copy to quarantine");
console.log("  cleanup-report    Compile cleanup status details and estimate ASR readiness impact");
console.log("  status            Print dashboard of all generated reports and blockers");
console.log("");
console.log("Example runs:");
console.log("  npm run audio-drop-verification -- \"help\"");
console.log("  npm run audio-drop-verification -- \"inventory\"");
console.log("  npm run audio-drop-verification -- \"match-sessions\"");
console.log("  npm run audio-drop-verification -- \"quarantine-check\"");
console.log("  npm run audio-drop-verification -- \"cleanup-report\"");
console.log("  npm run audio-drop-verification -- \"status\"");
console.log("=========================================");
