import { COMMAND_REGISTRY } from '../config/commands.js';

function printLiveMicrophoneAudioStreamerHelp() {
  console.log("=========================================");
  console.log("LIVE MICROPHONE AUDIO STREAMER DAEMON EXPANSION - HELP");
  console.log("=========================================");
  console.log("This module stages daemon configurations, scans local audio processing");
  console.log("models, validates pipeline connections, and simulates audio streaming");
  console.log("parameters -- all WITHOUT enabling live microphone access, spawning");
  console.log("daemon processes, or streaming audio.");
  console.log("\nCore Safety Rules Enforced:");
  console.log("  1. No Live Microphone: ALLOW_LIVE_MICROPHONE = false");
  console.log("  2. No Daemon Spawn: ALLOW_DAEMON_SPAWN = false");
  console.log("  3. No Audio Streaming: ALLOW_AUDIO_STREAMING = false");
  console.log("  4. No Cloud Processing: ALLOW_CLOUD_PROCESSING = false");
  console.log("  5. Human Approval Required: REQUIRE_HUMAN_APPROVAL = true");
  console.log("  6. Local Model Required: REQUIRE_LOCAL_MODEL_PRESENCE = true");
  console.log("  7. Read-Only Staging: All output is advisory and read-only");
  console.log("\n-----------------------------------------");
  console.log("  COMMANDS:");
  console.log("-----------------------------------------");
  console.log("\n  status");
  console.log("    Print module configuration, safety flags,");
  console.log("    upstream source status, daemon defaults,");
  console.log("    and supported model inventory.");
  console.log("\n  scan-models");
  console.log("    Scan local audio processing model directories");
  console.log("    for available Whisper, VAD, and ASR models");
  console.log("    and generate a compatibility report.");
  console.log("\n  configure-daemon");
  console.log("    Stage daemon configuration with audio capture");
  console.log("    parameters, backend selection, model assignment,");
  console.log("    and pipeline wiring status.");
  console.log("\n  validate-pipeline");
  console.log("    Validate streaming pipeline connections from");
  console.log("    sentinel-os audio bridge through VibeVoice");
  console.log("    listener to ASR orchestrator.");
  console.log("\n  stream-simulation");
  console.log("    Dry-run audio stream simulation computing");
  console.log("    buffer chain throughput, latency estimates,");
  console.log("    and configuration parameter validation.");
  console.log("\n  daemon-report");
  console.log("    Generate comprehensive daemon expansion");
  console.log("    readiness report checking all upstream sources,");
  console.log("    safety flags, and pipeline dependencies.");
  console.log("\n  obsidian-export");
  console.log("    Stage a streamer summary for Obsidian");
  console.log("    export via the Approved Write Gateway.");
  console.log("\n-----------------------------------------");
  console.log("  EXAMPLES:");
  console.log("-----------------------------------------");
  console.log("\n  npm run live-microphone-audio-streamer -- \"status\"");
  console.log("  npm run live-microphone-audio-streamer -- \"scan-models\"");
  console.log("  npm run live-microphone-audio-streamer -- \"configure-daemon\"");
  console.log("  npm run live-microphone-audio-streamer -- \"validate-pipeline\"");
  console.log("  npm run live-microphone-audio-streamer -- \"stream-simulation\"");
  console.log("  npm run live-microphone-audio-streamer -- \"daemon-report\"");
  console.log("  npm run live-microphone-audio-streamer -- \"obsidian-export\"");
  console.log("\n-----------------------------------------");
  console.log("  SAFETY:");
  console.log("-----------------------------------------");
  console.log("  - No live microphone access or audio capture");
  console.log("  - No daemon processes spawned");
  console.log("  - No audio streaming to any destination");
  console.log("  - No cloud-based audio processing");
  console.log("  - All simulations use computed estimates only");
  console.log("  - Human approval required for all transitions");
  console.log("  - Local model presence required before enabling");
  console.log("\n-----------------------------------------");
  console.log("  UPSTREAM SOURCES:");
  console.log("-----------------------------------------");
  console.log("  - Audio Bridge: sentinel-os/lib/audio-bridge.ts");
  console.log("  - ASR Listener: config/narrator-asr-listener.config.ts");
  console.log("  - ASR Orchestrator: config/asr-orchestrator.ts");
  console.log("  - ASR Backend: config/narrator-asr-backend.config.ts");
  console.log("  - ASR Model Gate: config/asr-model-gate.ts");
  console.log("  - VibeVoice Listener: scripts/vibevoice-listener.ts");
  console.log("  - Wake Word Listener: scripts/wake_word_listener.py");
  console.log("  - Whisper Models: local_assets/whisper_models/");

  console.log("\n-----------------------------------------");
  console.log("  REGISTERED COMMANDS:");
  console.log("-----------------------------------------");
  const targetCmds = COMMAND_REGISTRY.filter(c => c.name.includes('live-microphone-audio-streamer'));
  for (const cmd of targetCmds) {
    console.log(`\n  Command: npm run command -- "${cmd.name}"`);
    console.log(`   Description: ${cmd.description}`);
    console.log(`   Owning Agent: ${cmd.owningAgent}`);
    console.log(`   Risk Level:   ${cmd.riskLevel.toUpperCase()}`);
  }
  console.log("\n=========================================");
}

printLiveMicrophoneAudioStreamerHelp();
