import { COMMAND_REGISTRY } from '../config/commands.js';

function printMicroProductTreeGrooveConnectorHelp() {
  console.log("=========================================");
  console.log("MICRO-PRODUCT FACTORY TREE GROOVE RECORDS CONNECTOR - HELP");
  console.log("=========================================");
  console.log("This module bridges the SQLite ledger micro-product factory to");
  console.log("the Tree Groove Records release catalog. It stages, maps, and");
  console.log("compiles catalog connection artifacts offline -- all WITHOUT");
  console.log("ledger writes, catalog publishing, or external API calls.");
  console.log("\nCore Safety Rules Enforced:");
  console.log("  1. No Ledger Writes: ALLOW_LEDGER_WRITES = false");
  console.log("  2. No Catalog Publish: ALLOW_CATALOG_PUBLISH = false");
  console.log("  3. No External API Calls: ALLOW_EXTERNAL_API_CALLS = false");
  console.log("  4. Human Approval Required: REQUIRE_HUMAN_APPROVAL = true");
  console.log("  5. Catalog Review Required: REQUIRE_CATALOG_REVIEW = true");
  console.log("  6. No Direct Obsidian Write: ALLOW_DIRECT_OBSIDIAN_WRITE = false");
  console.log("\n-----------------------------------------");
  console.log("  COMMANDS:");
  console.log("-----------------------------------------");
  console.log("\n  status");
  console.log("    Print module configuration, safety flags,");
  console.log("    upstream source status, and output directory");
  console.log("    inventory.");
  console.log("\n  scan-products");
  console.log("    Scan micro-product ledger entries and compile");
  console.log("    catalog mapping candidates from upstream sources.");
  console.log("\n  map-catalog");
  console.log("    Map micro-product entries to Tree Groove Records");
  console.log("    release catalog format with release type");
  console.log("    classification.");
  console.log("\n  stage-release");
  console.log("    Stage a release package from mapped catalog entries");
  console.log("    for human review including platform readiness.");
  console.log("\n  distribution-plan");
  console.log("    Generate a platform distribution plan for staged");
  console.log("    releases with format and metadata requirements.");
  console.log("\n  connector-report");
  console.log("    Compile connector status report showing mapping");
  console.log("    coverage, staging status, and identified gaps.");
  console.log("\n  obsidian-export");
  console.log("    Stage connector summary for Obsidian export");
  console.log("    via the Approved Write Gateway.");
  console.log("\n-----------------------------------------");
  console.log("  EXAMPLES:");
  console.log("-----------------------------------------");
  console.log("\n  npm run micro-product-tree-groove-connector -- \"status\"");
  console.log("  npm run micro-product-tree-groove-connector -- \"scan-products\"");
  console.log("  npm run micro-product-tree-groove-connector -- \"map-catalog\"");
  console.log("  npm run micro-product-tree-groove-connector -- \"stage-release\"");
  console.log("  npm run micro-product-tree-groove-connector -- \"distribution-plan\"");
  console.log("  npm run micro-product-tree-groove-connector -- \"connector-report\"");
  console.log("  npm run micro-product-tree-groove-connector -- \"obsidian-export\"");
  console.log("\n-----------------------------------------");
  console.log("  SAFETY:");
  console.log("-----------------------------------------");
  console.log("  - No SQLite ledger modifications");
  console.log("  - No catalog publishing or distribution");
  console.log("  - No external API calls");
  console.log("  - All output is read-only staging");
  console.log("  - Release decisions require human operator");
  console.log("  - Catalog mappings are documentation only");
  console.log("\n-----------------------------------------");
  console.log("  UPSTREAM SOURCES:");
  console.log("-----------------------------------------");
  console.log("  - Micro-Product Factory: sentinel-os/lib/mesh_layer.ts");
  console.log("  - Campaign Data: outputs/campaigns/");
  console.log("  - Platform Verification: outputs/platform_verification/");
  console.log("\n-----------------------------------------");
  console.log("  RELEASE TYPES:");
  console.log("-----------------------------------------");
  console.log("  - single-track");
  console.log("  - ep-bundle");
  console.log("  - album-package");
  console.log("  - remix-collection");
  console.log("  - beat-pack");
  console.log("\n-----------------------------------------");
  console.log("  DISTRIBUTION PLATFORMS:");
  console.log("-----------------------------------------");
  console.log("  - Spotify");
  console.log("  - Apple Music");
  console.log("  - YouTube Music");
  console.log("  - SoundCloud");
  console.log("  - Bandcamp");
  console.log("  - TikTok");

  console.log("\n-----------------------------------------");
  console.log("  REGISTERED COMMANDS:");
  console.log("-----------------------------------------");
  const targetCmds = COMMAND_REGISTRY.filter(c => c.name.includes('micro-product-tree-groove-connector'));
  for (const cmd of targetCmds) {
    console.log(`\n  Command: npm run command -- "${cmd.name}"`);
    console.log(`   Description: ${cmd.description}`);
    console.log(`   Owning Agent: ${cmd.owningAgent}`);
    console.log(`   Risk Level:   ${cmd.riskLevel.toUpperCase()}`);
  }
  console.log("\n=========================================");
}

printMicroProductTreeGrooveConnectorHelp();
