import { COMMAND_REGISTRY } from '../config/commands.js';

function printObsidianSyncLayerHelp() {
  console.log("=========================================");
  console.log("OBSIDIAN SYNC LAYER - HELP");
  console.log("=========================================");
  console.log("This module provides unified vault sync orchestration, scanning");
  console.log("all Brilliantaire OS module export directories for Obsidian-ready");
  console.log("files, compiling sync manifests, previewing vault routing, and");
  console.log("reporting pipeline health -- all WITHOUT direct vault writes.");
  console.log("\nCore Safety Rules Enforced:");
  console.log("  1. No Direct Vault Write: ALLOW_DIRECT_VAULT_WRITE = false");
  console.log("  2. No Auto Sync: ALLOW_AUTO_SYNC = false");
  console.log("  3. No Vault Deletion: ALLOW_VAULT_DELETION = false");
  console.log("  4. No Vault Modification: ALLOW_VAULT_MODIFICATION = false");
  console.log("  5. No Direct Obsidian Write: ALLOW_DIRECT_OBSIDIAN_WRITE = false");
  console.log("  6. Human Approval Required: REQUIRE_HUMAN_APPROVAL = true");
  console.log("  7. Vault Presence Required: REQUIRE_VAULT_PRESENCE = true");
  console.log("\n-----------------------------------------");
  console.log("  COMMANDS:");
  console.log("-----------------------------------------");
  console.log("\n  status");
  console.log("    Print sync layer configuration, safety flags,");
  console.log("    vault detection, upstream source status, and");
  console.log("    pending staged file counts.");
  console.log("\n  discover-staged");
  console.log("    Scan all 16 module export directories for");
  console.log("    Obsidian-ready files matching configured");
  console.log("    glob patterns.");
  console.log("\n  compile-manifest");
  console.log("    Build a unified sync manifest of all pending");
  console.log("    exports with routing assignments, file sizes,");
  console.log("    and modification dates.");
  console.log("\n  preview-routes");
  console.log("    Preview where each staged file would be routed");
  console.log("    in the vault by matching filename prefixes to");
  console.log("    configured vault subfolder rules.");
  console.log("\n  sync-report");
  console.log("    Generate comprehensive sync health report");
  console.log("    checking pipeline coverage, safety flags,");
  console.log("    upstream sources, and module status.");
  console.log("\n  vault-health");
  console.log("    Check vault structure, subfolder presence,");
  console.log("    candidate path status, and routing coverage.");
  console.log("\n  obsidian-export");
  console.log("    Stage a sync layer summary for Obsidian");
  console.log("    export via the Approved Write Gateway.");
  console.log("\n-----------------------------------------");
  console.log("  EXAMPLES:");
  console.log("-----------------------------------------");
  console.log("\n  npm run obsidian-sync-layer -- \"status\"");
  console.log("  npm run obsidian-sync-layer -- \"discover-staged\"");
  console.log("  npm run obsidian-sync-layer -- \"compile-manifest\"");
  console.log("  npm run obsidian-sync-layer -- \"preview-routes\"");
  console.log("  npm run obsidian-sync-layer -- \"sync-report\"");
  console.log("  npm run obsidian-sync-layer -- \"vault-health\"");
  console.log("  npm run obsidian-sync-layer -- \"obsidian-export\"");
  console.log("\n-----------------------------------------");
  console.log("  SAFETY:");
  console.log("-----------------------------------------");
  console.log("  - No direct vault writes or modifications");
  console.log("  - No automatic synchronization");
  console.log("  - No vault file deletion or overwriting");
  console.log("  - All output is read-only staging");
  console.log("  - Human approval required for all sync decisions");
  console.log("  - Vault presence verified before health checks");
  console.log("\n-----------------------------------------");
  console.log("  MODULE EXPORT SOURCES:");
  console.log("-----------------------------------------");
  console.log("  - Write Gateway (core): outputs/write_staging/");
  console.log("  - Narrator Briefs: outputs/narrator/briefs/");
  console.log("  - Narrator Cards: outputs/narrator/cards/");
  console.log("  - Icyflamze Core: outputs/icyflamze_core/obsidian_staging/");
  console.log("  - NotebookLM Dashboard: outputs/notebooklm_bridge/obsidian_dashboard/markdown/");
  console.log("  - Higgsfield AI: outputs/higgsfield_ai/narrator_sync/");
  console.log("  - Render Intake: outputs/render_intake/scans/");
  console.log("  - Stripe Webhook: outputs/stripe_webhook_verification/");
  console.log("  - ZK Webhook: outputs/zk_webhook_verification/");
  console.log("  - Micro-Product Tree Groove: outputs/micro_product_tree_groove/");
  console.log("  - Live Microphone Streamer: outputs/live_microphone_audio_streamer/");
  console.log("  - ASR Human Approval: outputs/asr_human_approval_selection/");
  console.log("  - Grinders Keep Rerun: outputs/grinders_keep_verification_rerun/");
  console.log("  - Manual Implementation: outputs/manual_implementation_packet/");
  console.log("  - Platform Verification: outputs/platform_verification/reports/");
  console.log("  - Brilliantaire Briefs (repo): brilliantaire-briefs/");

  console.log("\n-----------------------------------------");
  console.log("  REGISTERED COMMANDS:");
  console.log("-----------------------------------------");
  const targetCmds = COMMAND_REGISTRY.filter(c => c.name.includes('obsidian-sync-layer'));
  for (const cmd of targetCmds) {
    console.log(`\n  Command: npm run command -- "${cmd.name}"`);
    console.log(`   Description: ${cmd.description}`);
    console.log(`   Owning Agent: ${cmd.owningAgent}`);
    console.log(`   Risk Level:   ${cmd.riskLevel.toUpperCase()}`);
  }
  console.log("\n=========================================");
}

printObsidianSyncLayerHelp();
