import { COMMAND_REGISTRY } from '../config/commands.js';

function printTreeGrooveReleasePipelineHelp() {
  console.log("=========================================");
  console.log("TREE GROOVE RECORDS RELEASE PIPELINE - HELP");
  console.log("=========================================");
  console.log("This module orchestrates release packaging, quality gates,");
  console.log("metadata validation, platform submission staging, and pipeline");
  console.log("reporting for Tree Groove Records releases — all WITHOUT");
  console.log("connecting to live distribution platforms.");
  console.log("\nCore Safety Rules Enforced:");
  console.log("  1. No Live Distribution: ALLOW_LIVE_DISTRIBUTION = false");
  console.log("  2. No Auto Submission: ALLOW_AUTO_SUBMISSION = false");
  console.log("  3. No Metadata Publish: ALLOW_METADATA_PUBLISH = false");
  console.log("  4. No External API Calls: ALLOW_EXTERNAL_API_CALLS = false");
  console.log("  5. Human Approval Required: REQUIRE_HUMAN_APPROVAL = true");
  console.log("  6. Quality Gate Required: REQUIRE_QUALITY_GATE_PASS = true");
  console.log("  7. No Direct Obsidian Write: ALLOW_DIRECT_OBSIDIAN_WRITE = false");
  console.log("\n-----------------------------------------");
  console.log("  COMMANDS:");
  console.log("-----------------------------------------");
  console.log("\n  status");
  console.log("    Print pipeline configuration, safety flags,");
  console.log("    upstream source status, release types,");
  console.log("    distribution platforms, and quality gate counts.");
  console.log("\n  assemble-package");
  console.log("    Scan connector catalog mappings and build");
  console.log("    release packages with asset checklists for");
  console.log("    each mapped release.");
  console.log("\n  quality-gate");
  console.log("    Run 18 quality gate checks across technical,");
  console.log("    artwork, metadata, and legal categories and");
  console.log("    produce pass/ready/blocked evaluation.");
  console.log("\n  validate-metadata");
  console.log("    Validate release metadata against all 6");
  console.log("    platform submission requirements (Spotify,");
  console.log("    Apple Music, YouTube Music, SoundCloud,");
  console.log("    Bandcamp, TikTok).");
  console.log("\n  stage-submission");
  console.log("    Stage platform submissions with prerequisite");
  console.log("    checks, per-platform readiness, and a 6-phase");
  console.log("    submission timeline.");
  console.log("\n  pipeline-report");
  console.log("    Generate a comprehensive pipeline status report");
  console.log("    with stage tracking, quality gate summaries,");
  console.log("    and submission readiness overview.");
  console.log("\n  obsidian-export");
  console.log("    Stage a pipeline summary for Obsidian export");
  console.log("    via the Approved Write Gateway.");
  console.log("\n-----------------------------------------");
  console.log("  EXAMPLES:");
  console.log("-----------------------------------------");
  console.log("\n  npm run tree-groove-release-pipeline -- \"status\"");
  console.log("  npm run tree-groove-release-pipeline -- \"assemble-package\"");
  console.log("  npm run tree-groove-release-pipeline -- \"quality-gate\"");
  console.log("  npm run tree-groove-release-pipeline -- \"validate-metadata\"");
  console.log("  npm run tree-groove-release-pipeline -- \"stage-submission\"");
  console.log("  npm run tree-groove-release-pipeline -- \"pipeline-report\"");
  console.log("  npm run tree-groove-release-pipeline -- \"obsidian-export\"");
  console.log("\n-----------------------------------------");
  console.log("  SAFETY:");
  console.log("-----------------------------------------");
  console.log("  - No live distribution platform connections");
  console.log("  - No automatic submission to any platform");
  console.log("  - No metadata publishing to external services");
  console.log("  - No external API calls");
  console.log("  - All output is read-only staging");
  console.log("  - Human approval required for all submissions");
  console.log("  - Quality gate pass required before staging");
  console.log("\n-----------------------------------------");
  console.log("  UPSTREAM SOURCES:");
  console.log("-----------------------------------------");
  console.log("  - Connector Config: config/micro-product-tree-groove-connector.ts");
  console.log("  - Connector Script: scripts/micro-product-tree-groove-connector.ts");
  console.log("  - Catalog Mappings: outputs/micro_product_tree_groove/catalog_mappings/");
  console.log("  - Release Staging: outputs/micro_product_tree_groove/release_staging/");
  console.log("  - Distribution Plans: outputs/micro_product_tree_groove/distribution_plans/");

  console.log("\n-----------------------------------------");
  console.log("  REGISTERED COMMANDS:");
  console.log("-----------------------------------------");
  const targetCmds = COMMAND_REGISTRY.filter(c => c.name.includes('tree-groove-release-pipeline'));
  for (const cmd of targetCmds) {
    console.log(`\n  Command: npm run command -- "${cmd.name}"`);
    console.log(`   Description: ${cmd.description}`);
    console.log(`   Owning Agent: ${cmd.owningAgent}`);
    console.log(`   Risk Level:   ${cmd.riskLevel.toUpperCase()}`);
  }
  console.log("\n=========================================");
}

printTreeGrooveReleasePipelineHelp();
