console.log("=========================================");
console.log("🎙️ OFFLINE TTS MODEL READINESS GATE HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run tts-model-gate -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help             Print this help guide");
console.log("  check            Scan local folder, audit matching ONNX/JSON pairs, and compile gate report");
console.log("  checklist        Generate structured model file eligibility checklist");
console.log("  manual-enable    Compile manual activation instructions and local env variable requirements");
console.log("  status           Print current model files check status and readiness metrics summary");
console.log("");
console.log("Example runs:");
console.log("  npm run tts-model-gate -- \"help\"");
console.log("  npm run tts-model-gate -- \"check\"");
console.log("  npm run tts-model-gate -- \"checklist\"");
console.log("  npm run tts-model-gate -- \"manual-enable\"");
console.log("  npm run tts-model-gate -- \"status\"");
console.log("=========================================");
