console.log("=========================================");
console.log("🎙️ OFFLINE TTS MODEL ACQUISITION HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run tts-model-acquisition -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help                 Print this help guide");
console.log("  guide                Generate the manual model acquisition instruction guide");
console.log("  inventory            Scan models/tts/piper/ folder and compile inventory list");
console.log("  verify-placement     Check whether a valid candidate pair exists for synthesis");
console.log("  next-step            Compile readiness metrics and list next required manual steps");
console.log("  status               Print summary checklist of local file presence and readiness");
console.log("");
console.log("Example runs:");
console.log("  npm run tts-model-acquisition -- \"help\"");
console.log("  npm run tts-model-acquisition -- \"guide\"");
console.log("  npm run tts-model-acquisition -- \"inventory\"");
console.log("  npm run tts-model-acquisition -- \"verify-placement\"");
console.log("  npm run tts-model-acquisition -- \"next-step\"");
console.log("  npm run tts-model-acquisition -- \"status\"");
console.log("=========================================");
