console.log("=========================================");
console.log("🎙️ OFFLINE TTS BRIEF COMPOSER HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run tts-brief-composer -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help             Print this help guide");
console.log("  short            Read narrator brief and compile a short TTS script");
console.log("  medium           Read narrator brief and compile a medium TTS script");
console.log("  long             Read narrator brief and compile a long deep-dive script");
console.log("  all              Compile short, medium, and long scripts from brief");
console.log("  queue-packet     Compile a structured queue packet file mapping scripts");
console.log("  voice-direction  Compile tone instructions and pacing directives file");
console.log("  status           Print current file states and metrics summary");
console.log("");
console.log("Example runs:");
console.log("  npm run tts-brief-composer -- \"help\"");
console.log("  npm run tts-brief-composer -- \"short\"");
console.log("  npm run tts-brief-composer -- \"medium\"");
console.log("  npm run tts-brief-composer -- \"long\"");
console.log("  npm run tts-brief-composer -- \"all\"");
console.log("  npm run tts-brief-composer -- \"queue-packet\"");
console.log("  npm run tts-brief-composer -- \"voice-direction\"");
console.log("  npm run tts-brief-composer -- \"status\"");
console.log("=========================================");
