console.log("=========================================");
console.log("🎙️ OFFLINE TTS MODEL ACTIVATION CHECK HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run tts-model-activation -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help                 Print this help guide");
console.log("  placement-guide      Generate structured manual model placement instructions guide");
console.log("  scan                 Audit models/tts/piper/ folder layout, file sizes, and empty states");
console.log("  pairing-check        Inspect if every voice model ONNX matches its config JSON file");
console.log("  activation-readiness Compile multi-layer validation state and determine if TTS can run");
console.log("  status               Print summary checklist of local file presence and readiness metrics");
console.log("");
console.log("Example runs:");
console.log("  npm run tts-model-activation -- \"help\"");
console.log("  npm run tts-model-activation -- \"placement-guide\"");
console.log("  npm run tts-model-activation -- \"scan\"");
console.log("  npm run tts-model-activation -- \"pairing-check\"");
console.log("  npm run tts-model-activation -- \"activation-readiness\"");
console.log("  npm run tts-model-activation -- \"status\"");
console.log("=========================================");
