console.log("=========================================");
console.log("🎙️ OFFLINE TTS QUEUE VALIDATOR HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run tts-queue-validator -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help             Print this help guide");
console.log("  validate         Run full syntax, limits, and integrity validation scans");
console.log("  checklist        Compile structured requirement eligibility checklists");
console.log("  risk-report      Scan for shell-injection chars, URL references, and gaps");
console.log("  status           Print current file states and validation score summary");
console.log("");
console.log("Example runs:");
console.log("  npm run tts-queue-validator -- \"help\"");
console.log("  npm run tts-queue-validator -- \"validate\"");
console.log("  npm run tts-queue-validator -- \"checklist\"");
console.log("  npm run tts-queue-validator -- \"risk-report\"");
console.log("  npm run tts-queue-validator -- \"status\"");
console.log("=========================================");
