console.log("=========================================");
console.log("🎙️ OFFLINE TTS SYNTHESIZER SCAPPHOLD HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run tts-synthesizer -- <command>");
console.log("");
console.log("Available commands:");
console.log("  help             Print this help guide");
console.log("  config-report    Verify safety constraints and compile engine parameters report");
console.log("  model-check      Inspect local model directory for manual model placement check");
console.log("  dry-run          Simulate offline voice compilation command preview and dry-run output");
console.log("  manifest         Generate structured manifest for predicted audio outputs");
console.log("  status           Print current file states and synthesis capabilities metrics");
console.log("");
console.log("Example runs:");
console.log("  npm run tts-synthesizer -- \"help\"");
console.log("  npm run tts-synthesizer -- \"config-report\"");
console.log("  npm run tts-synthesizer -- \"model-check\"");
console.log("  npm run tts-synthesizer -- \"dry-run\"");
console.log("  npm run tts-synthesizer -- \"manifest\"");
console.log("  npm run tts-synthesizer -- \"status\"");
console.log("=========================================");
