console.log("=========================================");
console.log("🎙️ OFFLINE VOICE SESSION RECORDER HELP");
console.log("=========================================");
console.log("");
console.log("Usage: npm run voice-session-recorder -- <command> [options]");
console.log("");
console.log("Available commands:");
console.log("  help                                 Print this help guide");
console.log("  guide                                Generate manual recording configuration manual");
console.log("  create-session <session-type>        Initialize metadata for a new drop session");
console.log("                                       (e.g., \"create-session narrator briefing\")");
console.log("  scan-recordings                      Scan voice_sessions/manual_recordings/ for file inventory");
console.log("  review                               Audit matching audio file format, sizes and ASR eligibility");
console.log("  stage-transcription                  Create STAGE records for validated audio files (no ASR run)");
console.log("  status                               Print summary overview of staged sessions and readiness");
console.log("");
console.log("Session Types available for create-session:");
console.log("  narrator briefing");
console.log("  oracle voice note");
console.log("  campaign command voice");
console.log("  grounded insight read");
console.log("  system status readout");
console.log("");
console.log("Example runs:");
console.log("  npm run voice-session-recorder -- \"help\"");
console.log("  npm run voice-session-recorder -- \"guide\"");
console.log("  npm run voice-session-recorder -- \"create-session narrator briefing\"");
console.log("  npm run voice-session-recorder -- \"scan-recordings\"");
console.log("  npm run voice-session-recorder -- \"review\"");
console.log("  npm run voice-session-recorder -- \"stage-transcription\"");
console.log("  npm run voice-session-recorder -- \"status\"");
console.log("=========================================");
