#!/usr/bin/env python3
import os
import sys
import re
import json
import yaml
import argparse

def parse_markdown_workflow(file_path):
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Workflow file not found at: {file_path}")

    with open(file_path, "r", encoding="utf-8") as f:
        raw_content = f.read()

    # Split frontmatter
    yaml_metadata = {}
    content = raw_content
    if raw_content.startswith("---"):
        parts = raw_content.split("---", 2)
        if len(parts) >= 3:
            try:
                yaml_metadata = yaml.safe_load(parts[1]) or {}
            except Exception as e:
                print(f"[!] Error parsing YAML frontmatter: {e}", file=sys.stderr)
            content = parts[2]

    # Find Agent Title (First # heading)
    title_match = re.search(r"^#\s+(.*)", content, re.MULTILINE)
    agent_name = title_match.group(1).strip() if title_match else "Autogen Agent"

    # Extract sections using regex
    sections = {}
    current_section = None
    section_content = []

    for line in content.split("\n"):
        header_match = re.match(r"^##\s+(.*)", line)
        if header_match:
            if current_section:
                sections[current_section] = "\n".join(section_content).strip()
            current_section = header_match.group(1).strip().lower()
            section_content = []
        else:
            section_content.append(line)

    if current_section:
        sections[current_section] = "\n".join(section_content).strip()

    # Parse Inputs
    inputs = []
    inputs_text = sections.get("inputs", "")
    # Find list items: - `name` (type): description. Default: val
    input_items = re.findall(r"^-\s+`([^`]+)`\s+\(([^)]+)\):\s*(.*?)(?:\.\s*Default:\s*(.*))?$", inputs_text, re.MULTILINE)
    
    for item in input_items:
        name = item[0].strip()
        var_type = item[1].strip().lower()
        desc = item[2].strip()
        default_val = item[3].strip() if len(item) > 3 else "None"
        
        # Parse default value
        if default_val.lower() == "null" or default_val == "":
            default_val = "None"
        elif var_type == "boolean":
            default_val = "True" if default_val.lower() in ("true", "yes", "1") else "False"
        elif var_type == "integer":
            try:
                default_val = str(int(default_val))
            except ValueError:
                default_val = "None"
        elif var_type == "array":
            # Strip brackets and split by comma if list
            clean_val = re.sub(r"[\[\]'\"]", "", default_val)
            if clean_val.lower() == "none" or clean_val.lower() == "null" or not clean_val:
                default_val = "[]"
            else:
                items = [x.strip() for x in clean_val.split(",")]
                default_val = str(items)
        
        inputs.append({
            "name": name,
            "type": var_type,
            "description": desc,
            "default": default_val
        })

    # Parse Output JSON
    output_json_block = ""
    output_json_text = sections.get("output json", "")
    json_match = re.search(r"```json\s*(.*?)\s*```", output_json_text, re.DOTALL)
    if json_match:
        output_json_block = json_match.group(1).strip()
    else:
        # Try finding standard JSON inside the block
        json_match_fallback = re.search(r"({.*})", output_json_text, re.DOTALL)
        if json_match_fallback:
            output_json_block = json_match_fallback.group(1).strip()

    # Parse Rules
    rules = []
    rules_text = sections.get("rules", "")
    rule_items = re.findall(r"^-\s+(.*)$", rules_text, re.MULTILINE)
    for rule in rule_items:
        rules.append(rule.strip())

    # Parse Failure Codes
    failure_codes = []
    failure_codes_text = sections.get("failure codes", "")
    # Match - **CODE**: Description
    code_items = re.findall(r"^-\s+\*\*([^*]+)\*\*:\s*(.*)$", failure_codes_text, re.MULTILINE)
    for code, desc in code_items:
        failure_codes.append({
            "code": code.strip(),
            "description": desc.strip()
        })

    return {
        "agent_name": agent_name,
        "description": yaml_metadata.get("description", "Autogenerated agent script from workflow."),
        "inputs": inputs,
        "output_json_template": output_json_block,
        "rules": rules,
        "failure_codes": failure_codes
    }

def generate_python_script(metadata):
    agent_name = metadata["agent_name"]
    description = metadata["description"]
    safe_name = agent_name.replace(" ", "").replace("Agent", "")
    filename_prefix = agent_name.lower().replace(" ", "_")

    # Arguments generation
    arg_lines = []
    for inp in metadata["inputs"]:
        name = inp["name"]
        var_type = inp["type"]
        desc = inp["description"].replace('"', '\\"')
        default = inp["default"]

        arg_name = f"--{name.replace('_', '-')}"
        
        if var_type == "boolean":
            # Handle boolean logic correctly with argparse
            arg_lines.append(
                f"    parser.add_argument('{arg_name}', action='store_true', "
                f"default={default}, help=\"{desc}\")"
            )
        elif var_type == "integer":
            arg_lines.append(
                f"    parser.add_argument('{arg_name}', type=int, "
                f"default={default}, help=\"{desc}\")"
            )
        elif var_type == "array":
            arg_lines.append(
                f"    parser.add_argument('{arg_name}', nargs='*', "
                f"default={default}, help=\"{desc}\")"
            )
        else:
            # string or other
            default_str = f"'{default}'" if default != "None" else "None"
            arg_lines.append(
                f"    parser.add_argument('{arg_name}', type=str, "
                f"default={default_str}, help=\"{desc}\")"
            )

    args_setup = "\n".join(arg_lines)

    # Output Template JSON dict
    output_dict_str = "    output_data = {\n"
    if metadata["output_json_template"]:
        try:
            # Clean up the output template JSON so it's a valid python dict structure
            cleaned_json = re.sub(r'"\.\.\."', 'None', metadata["output_json_template"])
            cleaned_json = re.sub(r'//.*', '', cleaned_json) # strip comments
            # Just structure as template comments or raw dictionary
            output_dict_str += f"        # Matches spec:\n"
            for line in cleaned_json.split("\n"):
                output_dict_str += f"        # {line}\n"
        except Exception:
            pass
    output_dict_str += "        \"success\": True,\n        \"failure_code\": \"\"\n    }"

    # Failure Codes definitions
    codes_def = ""
    for code_item in metadata["failure_codes"]:
        codes_def += f"    # {code_item['code']}: {code_item['description']}\n"

    # Rules translation into comments
    rules_comments = ""
    for idx, rule in enumerate(metadata["rules"], 1):
        rules_comments += f"    # Rule {idx}: {rule}\n"

    template = f"""#!/usr/bin/env python3
\"\"\"
Agent script for {agent_name}.
{description}

Autogenerated by workflow_to_script.py.
\"\"\"

import os
import sys
import json
import argparse
import subprocess
import logging
from datetime import datetime

# Setup Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("{safe_name}")

# Voice Narrative Bridge Helpers
VNP_BRIDGE_PATH = os.path.expanduser("~/.agents/voice_narrative.sh")

def announce_intent(message):
    logger.info(f"[VNP Intent] {{message}}")
    if os.path.exists(VNP_BRIDGE_PATH):
        try:
            subprocess.run(
                f"source {{VNP_BRIDGE_PATH}} && announce_intent \\\"{{message}}\\\"",
                shell=True,
                executable="/bin/zsh"
            )
        except Exception as e:
            logger.warning(f"Failed to announce VNP intent: {{e}}")

def announce_completion(message, score="25"):
    logger.info(f"[VNP Completion] {{message}} (Score: {{score}})")
    if os.path.exists(VNP_BRIDGE_PATH):
        try:
            subprocess.run(
                f"source {{VNP_BRIDGE_PATH}} && announce_completion \\\"{{message}}\\\" \\\"{{score}}\\\"",
                shell=True,
                executable="/bin/zsh"
            )
        except Exception as e:
            logger.warning(f"Failed to announce VNP completion: {{e}}")

# Failure Codes Constants
{codes_def}

def execute_agent_logic(args):
    \"\"\"
    Main logic execution for {agent_name}.
    \"\"\"
    logger.info("Executing logic rules...")
    
{rules_comments}
    
    # TODO: Implement step-by-step logic here
    
{output_dict_str}
    
    return output_data

def main():
    parser = argparse.ArgumentParser(description="{description}")
{args_setup}
    args = parser.parse_args()

    # Announce Intent via VNP voice bridge
    intent_msg = f"Executing {agent_name} logic with inputs: {{vars(args)}}"
    announce_intent(intent_msg)

    try:
        results = execute_agent_logic(args)
        
        # Verify success or print results
        print(json.dumps(results, indent=2))
        
        # Announce Completion
        if results.get("failure_code"):
            announce_completion(f"{agent_name} execution completed with error: {{results['failure_code']}}", "0")
            sys.exit(1)
        else:
            announce_completion(f"{agent_name} successfully executed operations.", "25")
            sys.exit(0)
            
    except Exception as e:
        logger.exception(f"Unhandled error in agent execution")
        announce_completion(f"{agent_name} execution encountered an unhandled exception.", "0")
        sys.exit(2)

if __name__ == "__main__":
    main()
"""
    return template

def main():
    parser = argparse.ArgumentParser(description="Generate executable Python agent skeletons from Markdown workflows.")
    parser.add_argument("workflow_file", help="Path to the workflow markdown file (e.g. .agents/workflows/reposcout_agent.md)")
    parser.add_argument("-o", "--output", help="Optional path to output script. If not set, saves to scripts/agent_<name>.py")
    args = parser.parse_args()

    try:
        metadata = parse_markdown_workflow(args.workflow_file)
        script_content = generate_python_script(metadata)
        
        if args.output:
            out_path = args.output
        else:
            filename = metadata["agent_name"].lower().replace(" ", "_") + ".py"
            out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)

        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(script_content)

        # Make executable
        os.chmod(out_path, 0o755)
        print(f"[+] Successfully generated executable agent script at: {out_path}")
        
    except Exception as e:
        print(f"[!] Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
