import { COMMAND_REGISTRY } from '../config/commands.js';

function printZkWebhookVerificationHelp() {
  console.log("=========================================");
  console.log("ZERO-KNOWLEDGE WEBHOOK TRANSACTION VERIFICATION PROOFS - HELP");
  console.log("=========================================");
  console.log("This module compiles and verifies ZK proofs for webhook transaction");
  console.log("payloads using SHA-256 hash chains under strict offline safety");
  console.log("constraints. All verification is manual-first with no live execution.");
  console.log("\nCore Safety Rules Enforced:");
  console.log("  1. No Live Verification: ALLOW_LIVE_VERIFICATION = false");
  console.log("  2. No Production Payloads: ALLOW_PRODUCTION_PAYLOAD_ACCESS = false");
  console.log("  3. No External API Calls: ALLOW_EXTERNAL_API_CALLS = false");
  console.log("  4. Human Approval Required: REQUIRE_HUMAN_APPROVAL = true");
  console.log("  5. Proof Review Required: REQUIRE_PROOF_REVIEW = true");
  console.log("  6. Read-Only Staging: All output is advisory and read-only");
  console.log("\n-----------------------------------------");
  console.log("  COMMANDS:");
  console.log("-----------------------------------------");
  console.log("\n  status");
  console.log("    Print module configuration, safety flags,");
  console.log("    upstream source status, and output directory");
  console.log("    inventory.");
  console.log("\n  compile-proofs");
  console.log("    Compile ZK proof documents from mock transaction");
  console.log("    data using SHA-256 hash chains. Generates proof");
  console.log("    compilations for all defined proof types.");
  console.log("\n  integrity-report");
  console.log("    Generate integrity verification report across");
  console.log("    all proof compilations. Summarizes compilation");
  console.log("    inventory, hash algorithm coverage, and status.");
  console.log("\n  audit-payloads");
  console.log("    Scan and audit webhook payload structures for");
  console.log("    proof compatibility. Checks upstream sources and");
  console.log("    validates field requirements per proof type.");
  console.log("\n  verify-chain");
  console.log("    Run offline hash chain verification against");
  console.log("    compiled proofs. Dry-run only — no live systems");
  console.log("    are contacted.");
  console.log("\n  proof-summary");
  console.log("    Generate human-readable summary of all proof");
  console.log("    compilations and verification states.");
  console.log("\n  obsidian-export");
  console.log("    Stage verification summary for Obsidian export");
  console.log("    via the Approved Write Gateway.");
  console.log("\n-----------------------------------------");
  console.log("  EXAMPLES:");
  console.log("-----------------------------------------");
  console.log("\n  npm run zk-webhook-verification -- \"status\"");
  console.log("  npm run zk-webhook-verification -- \"compile-proofs\"");
  console.log("  npm run zk-webhook-verification -- \"integrity-report\"");
  console.log("  npm run zk-webhook-verification -- \"audit-payloads\"");
  console.log("  npm run zk-webhook-verification -- \"verify-chain\"");
  console.log("  npm run zk-webhook-verification -- \"proof-summary\"");
  console.log("  npm run zk-webhook-verification -- \"obsidian-export\"");
  console.log("\n-----------------------------------------");
  console.log("  SAFETY:");
  console.log("-----------------------------------------");
  console.log("  - No live verification against production systems");
  console.log("  - No production payload data access");
  console.log("  - No external API calls");
  console.log("  - All output is read-only staging");
  console.log("  - Proof review requires human operator");
  console.log("  - Hash chains computed from mock data only");
  console.log("\n-----------------------------------------");
  console.log("  UPSTREAM SOURCES:");
  console.log("-----------------------------------------");
  console.log("  - Mesh Layer ZK Audit: sentinel-os/lib/mesh_layer.ts");
  console.log("  - ZK Audit API: sentinel-os/app/api/mesh/zk-audit/");
  console.log("  - Stripe Webhook Verification: outputs/stripe_webhook_verification/");
  console.log("\n-----------------------------------------");
  console.log("  PROOF TYPES:");
  console.log("-----------------------------------------");
  console.log("  - payload-hash-chain");
  console.log("  - transaction-integrity-proof");
  console.log("  - settlement-receipt-proof");
  console.log("  - ledger-consistency-proof");
  console.log("  - webhook-signature-proof");

  console.log("\n-----------------------------------------");
  console.log("  REGISTERED COMMANDS:");
  console.log("-----------------------------------------");
  const targetCmds = COMMAND_REGISTRY.filter(c => c.name.includes('zk-webhook-verification'));
  for (const cmd of targetCmds) {
    console.log(`\n  Command: npm run command -- "${cmd.name}"`);
    console.log(`   Description: ${cmd.description}`);
    console.log(`   Owning Agent: ${cmd.owningAgent}`);
    console.log(`   Risk Level:   ${cmd.riskLevel.toUpperCase()}`);
  }
  console.log("\n=========================================");
}

printZkWebhookVerificationHelp();
