import { ModelRecord } from './ModelTypes.js';

export const defaultModelProfiles: ModelRecord[] = [
  // Google Gemini
  {
    id: 'gemini-1.5-pro',
    provider: 'Google Gemini',
    displayName: 'Gemini 1.5 Pro',
    version: '1.5-pro-v1',
    status: 'Available',
    contextWindow: 2000000,
    supportsVision: true,
    supportsVoice: true,
    supportsReasoning: true,
    supportsCoding: true,
    supportsResearch: true,
    supportsAgents: true,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'medium',
    estimatedCost: 'medium',
    recommendedTasks: ['Builder', 'Research', 'Documentation', 'Executive Reports', 'Skill Discovery', 'Knowledge Summarizer'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'vision', 'voice', 'reasoning', 'coding', 'research', 'agents', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  {
    id: 'gemini-1.5-flash',
    provider: 'Google Gemini',
    displayName: 'Gemini 1.5 Flash',
    version: '1.5-flash-v1',
    status: 'Available',
    contextWindow: 1000000,
    supportsVision: true,
    supportsVoice: true,
    supportsReasoning: false,
    supportsCoding: true,
    supportsResearch: false,
    supportsAgents: false,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'fast',
    estimatedCost: 'low',
    recommendedTasks: ['Conversation', 'Voice Assistant', 'Workflow Planner'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'vision', 'voice', 'coding', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  {
    id: 'gemini-2.0-flash',
    provider: 'Google Gemini',
    displayName: 'Gemini 2.0 Flash (Deprecated)',
    version: '2.0-flash-v1',
    status: 'Available',
    contextWindow: 1000000,
    supportsVision: true,
    supportsVoice: true,
    supportsReasoning: false,
    supportsCoding: true,
    supportsResearch: false,
    supportsAgents: false,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'fast',
    estimatedCost: 'low',
    recommendedTasks: ['Conversation', 'Voice Assistant', 'Workflow Planner'],
    supported: true,
    deprecated: true,
    retirementDate: '2026-06-01T00:00:00Z',
    capabilities: ['text', 'vision', 'voice', 'coding', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  // Anthropic Claude
  {
    id: 'claude-3-5-sonnet',
    provider: 'Anthropic',
    displayName: 'Claude 3.5 Sonnet',
    version: '3.5-sonnet-v1',
    status: 'Available',
    contextWindow: 200000,
    supportsVision: true,
    supportsVoice: false,
    supportsReasoning: true,
    supportsCoding: true,
    supportsResearch: true,
    supportsAgents: true,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'fast',
    estimatedCost: 'medium',
    recommendedTasks: ['Builder', 'Architecture Reviewer', 'Debugger', 'Writing'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'vision', 'reasoning', 'coding', 'research', 'agents', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  {
    id: 'claude-3-opus',
    provider: 'Anthropic',
    displayName: 'Claude 3 Opus',
    version: '3-opus-v1',
    status: 'Available',
    contextWindow: 200000,
    supportsVision: true,
    supportsVoice: false,
    supportsReasoning: true,
    supportsCoding: true,
    supportsResearch: true,
    supportsAgents: false,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'slow',
    estimatedCost: 'high',
    recommendedTasks: ['Architecture Reviewer', 'Writing'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'vision', 'reasoning', 'coding', 'research', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  // OpenAI
  {
    id: 'gpt-4o',
    provider: 'OpenAI',
    displayName: 'GPT-4o',
    version: '4o-v1',
    status: 'Disconnected',
    contextWindow: 128000,
    supportsVision: true,
    supportsVoice: true,
    supportsReasoning: true,
    supportsCoding: true,
    supportsResearch: true,
    supportsAgents: true,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'fast',
    estimatedCost: 'high',
    recommendedTasks: ['Debugger', 'Workflow Planner', 'Writing'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'vision', 'voice', 'reasoning', 'coding', 'research', 'agents', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  {
    id: 'gpt-4-turbo',
    provider: 'OpenAI',
    displayName: 'GPT-4 Turbo',
    version: '4-turbo-v1',
    status: 'Configured',
    contextWindow: 128000,
    supportsVision: true,
    supportsVoice: false,
    supportsReasoning: true,
    supportsCoding: true,
    supportsResearch: false,
    supportsAgents: false,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'medium',
    estimatedCost: 'high',
    recommendedTasks: ['Architecture Reviewer', 'Debugger'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'vision', 'reasoning', 'coding', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  // Open Source
  {
    id: 'llama-3.1-405b',
    provider: 'Open Source',
    displayName: 'Llama 3.1 405B',
    version: '3.1-405b-v1',
    status: 'Unavailable',
    contextWindow: 128000,
    supportsVision: false,
    supportsVoice: false,
    supportsReasoning: true,
    supportsCoding: true,
    supportsResearch: true,
    supportsAgents: false,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'medium',
    estimatedCost: 'low',
    recommendedTasks: ['Research', 'Writing', 'Knowledge Summarizer'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'reasoning', 'coding', 'research', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  // Local
  {
    id: 'local-llama3',
    provider: 'Local',
    displayName: 'Local Llama 3',
    version: '3-8b-local',
    status: 'Unavailable',
    contextWindow: 8192,
    supportsVision: false,
    supportsVoice: false,
    supportsReasoning: false,
    supportsCoding: true,
    supportsResearch: false,
    supportsAgents: false,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    estimatedSpeed: 'fast',
    estimatedCost: 'low',
    recommendedTasks: ['Conversation', 'Documentation'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'coding', 'streaming'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  },
  // MCP Providers
  {
    id: 'mcp-assistant-model',
    provider: 'MCP',
    displayName: 'MCP Assistant Model',
    version: '1.0.0',
    status: 'Disconnected',
    contextWindow: 32000,
    supportsVision: false,
    supportsVoice: false,
    supportsReasoning: false,
    supportsCoding: true,
    supportsResearch: false,
    supportsAgents: true,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    estimatedSpeed: 'fast',
    estimatedCost: 'low',
    recommendedTasks: ['Conversation', 'Skill Discovery'],
    supported: true,
    deprecated: false,
    capabilities: ['text', 'coding', 'agents', 'streaming', 'function-calling'],
    discoveredAt: '2026-01-01T00:00:00Z',
    source: 'hardcoded'
  }
];
