import { createStudyRecord } from './StudyRecord.js';

export const INITIAL_STUDY_PACK = [
  createStudyRecord({
    id: 'study-adr',
    title: 'Architecture Decision Records',
    category: 'architecture',
    summary: 'A governed record format for capturing durable technical decisions.',
    what: 'An ADR documents the problem, decision, alternatives, and tradeoffs.',
    why: 'It prevents decision loss and reduces repeated architecture debates.',
    whenToUse: 'Use when a decision will affect multiple files, services, or future work.',
    whenNotToUse: 'Do not use for transient implementation details or trivial one-line fixes.',
    prerequisites: ['A concrete decision topic', 'At least one alternative', 'A durable storage path'],
    implementationMethod: 'Draft the decision, compare options, capture consequences, and store the final note beside the code or docs.',
    verificationMethod: 'Check that the decision can be retraced, justified, and linked to the impacted work.',
    rollbackMethod: 'Append a superseding ADR that explains the replacement decision and why it changed.',
    tradeoffs: ['More upfront writing', 'Less decision drift later'],
    risks: ['Over-documenting low-impact decisions'],
    evidence: ['Existing architecture freeze and change management patterns'],
    sources: [
      { title: 'Google Engineering Practices', url: 'https://google.github.io/eng-practices/', tier: 'tier2', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['engineering', 'documentation'],
    affectedServices: ['architecture review'],
    expectedOutcome: 'Architecture decisions become searchable and reviewable.',
    measurableIndicators: ['Decision traceability improves', 'Repeated debate decreases'],
    recommendation: 'pilot',
    confidence: 88,
    status: 'verified',
    relatedSkillIds: ['architecture-decision-records'],
    knowledgeNodeIds: ['doc:adr']
  }),
  createStudyRecord({
    id: 'study-prr',
    title: 'Production Readiness Reviews',
    category: 'release',
    summary: 'A release gate that validates readiness before a production cutover.',
    what: 'A PRR checks operational readiness, observability, and rollback posture.',
    why: 'It protects live systems from avoidable launch defects.',
    whenToUse: 'Use before production deployment or major cutovers.',
    whenNotToUse: 'Do not use for isolated local changes with no rollout impact.',
    prerequisites: ['Release candidate exists', 'Metrics and alerts are defined', 'Rollback plan is written'],
    implementationMethod: 'Review the release checklist, validate monitors, confirm owners, and sign off only when all gates are green.',
    verificationMethod: 'Verify the release can be reversed and observed without guesswork.',
    rollbackMethod: 'Disable release, restore previous artifact, and confirm service health.',
    tradeoffs: ['Slightly slower release cadence', 'Higher confidence at launch'],
    risks: ['Checklist fatigue if the gate becomes ceremonial'],
    evidence: ['Release governance patterns and operational checklists'],
    sources: [
      { title: 'AWS Well-Architected Framework', url: 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html', tier: 'tier1', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['release', 'operations'],
    affectedServices: ['deployments'],
    expectedOutcome: 'Launches happen with known rollback and verification paths.',
    measurableIndicators: ['Release failure rate drops', 'Rollback latency improves'],
    recommendation: 'pilot',
    confidence: 90,
    status: 'verified',
    relatedSkillIds: ['production-readiness-review'],
    knowledgeNodeIds: ['doc:prr']
  }),
  createStudyRecord({
    id: 'study-incident',
    title: 'Incident Management',
    category: 'incident',
    summary: 'A repeatable path for detecting, responding to, and learning from incidents.',
    what: 'Incident management coordinates triage, response, communication, and recovery.',
    why: 'It limits damage and keeps response actions consistent.',
    whenToUse: 'Use when user impact, data risk, or service degradation is present.',
    whenNotToUse: 'Do not use for routine maintenance or controlled experiments.',
    prerequisites: ['On-call ownership', 'Incident severity definitions', 'Communication channels'],
    implementationMethod: 'Classify severity, assign roles, restore service, and log follow-up actions.',
    verificationMethod: 'Confirm each incident produces a response log and follow-up review.',
    rollbackMethod: 'Fail back to the last stable state or disable the offending change.',
    tradeoffs: ['Requires operator attention', 'Reduces time to recovery'],
    risks: ['Misclassification can delay the right response'],
    evidence: ['SRE incident response patterns'],
    sources: [
      { title: 'Google SRE Book', url: 'https://sre.google/sre-book/table-of-contents/', tier: 'tier1', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['operations', 'support'],
    affectedServices: ['incidents'],
    expectedOutcome: 'Incidents are handled with consistent triage and closure.',
    measurableIndicators: ['MTTR decreases', 'Incident follow-up completion rises'],
    recommendation: 'pilot',
    confidence: 92,
    status: 'verified',
    relatedSkillIds: ['incident-management'],
    knowledgeNodeIds: ['doc:incident-management']
  }),
  createStudyRecord({
    id: 'study-observability',
    title: 'Observability',
    category: 'observability',
    summary: 'A structured way to understand system health through signals, not guesses.',
    what: 'Observability combines logs, metrics, traces, and meaningful alerts.',
    why: 'It shortens diagnosis time and improves recovery quality.',
    whenToUse: 'Use for any service that needs diagnosis, scaling, or incident response.',
    whenNotToUse: 'Do not use as a substitute for good design or validation.',
    prerequisites: ['Telemetry hooks', 'Dashboards', 'Alert ownership'],
    implementationMethod: 'Instrument the system, set thresholds, and review what the signals say under load.',
    verificationMethod: 'Exercise the dashboard and alerts during a known failure or load scenario.',
    rollbackMethod: 'Disable noisy alerts and revert telemetry changes while preserving core metrics.',
    tradeoffs: ['More instrumentation work', 'Better diagnosis speed'],
    risks: ['Too many low-value alerts'],
    evidence: ['Production telemetry and incident debugging patterns'],
    sources: [
      { title: 'AWS Well-Architected Framework', url: 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html', tier: 'tier1', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['observability', 'operations'],
    affectedServices: ['telemetry'],
    expectedOutcome: 'Teams can explain behavior from live signals.',
    measurableIndicators: ['Alert precision improves', 'Diagnosis time falls'],
    recommendation: 'pilot',
    confidence: 91,
    status: 'verified',
    relatedSkillIds: ['observability-design'],
    knowledgeNodeIds: ['doc:observability']
  }),
  createStudyRecord({
    id: 'study-release-engineering',
    title: 'Release Engineering',
    category: 'release',
    summary: 'A disciplined path from validated build to production release.',
    what: 'Release engineering manages packaging, promotion, verification, and cutover.',
    why: 'It lowers deployment risk and gives release work a predictable shape.',
    whenToUse: 'Use for user-visible releases and production deployments.',
    whenNotToUse: 'Do not use for tiny local-only iterations with no promotion path.',
    prerequisites: ['Build artifact', 'Versioning scheme', 'Release owner'],
    implementationMethod: 'Package the artifact, validate dependencies, run release checks, and promote through the approved path.',
    verificationMethod: 'Confirm version, checksum, and deployment status after release.',
    rollbackMethod: 'Deploy the prior version and confirm service health before reopening traffic.',
    tradeoffs: ['Adds release ceremony', 'Reduces release surprises'],
    risks: ['Version drift if packaging is inconsistent'],
    evidence: ['Release process and rollback policy'],
    sources: [
      { title: 'Microsoft Engineering Docs', url: 'https://microsoft.github.io/code-with-engineering-playbook/', tier: 'tier2', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['release', 'engineering'],
    affectedServices: ['builds', 'deploys'],
    expectedOutcome: 'Release steps are repeatable and reversible.',
    measurableIndicators: ['Release success rate rises', 'Post-release hotfixes fall'],
    recommendation: 'watch',
    confidence: 84,
    status: 'verified',
    relatedSkillIds: ['release-engineering'],
    knowledgeNodeIds: ['doc:release-engineering']
  }),
  createStudyRecord({
    id: 'study-testing-rollback',
    title: 'Automated Testing and Rollback',
    category: 'testing',
    summary: 'A coupled test-and-recovery practice for safer changes.',
    what: 'The practice verifies behavior automatically and defines how to retreat when the test or release fails.',
    why: 'It protects delivery speed without removing safety.',
    whenToUse: 'Use whenever a change could break production behavior.',
    whenNotToUse: 'Do not use to justify skipping baseline validation.',
    prerequisites: ['Automated tests', 'Rollback path', 'Ownership for failures'],
    implementationMethod: 'Run tests in the pipeline, gate promotion on success, and keep a rollback script available.',
    verificationMethod: 'Break the happy path in a safe environment and confirm the rollback path restores service.',
    rollbackMethod: 'Revert to the previous passing build and redeploy.',
    tradeoffs: ['More test maintenance', 'Less recovery risk'],
    risks: ['False confidence if tests are weak'],
    evidence: ['CI validation and rollback workflows'],
    sources: [
      { title: 'GitHub Docs', url: 'https://docs.github.com/', tier: 'tier1', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['testing', 'release'],
    affectedServices: ['pipelines'],
    expectedOutcome: 'Failures are caught early and reverted cleanly.',
    measurableIndicators: ['Rollback execution time improves', 'Escaped defects decrease'],
    recommendation: 'pilot',
    confidence: 89,
    status: 'verified',
    relatedSkillIds: ['recovery-testing', 'automated-rollback'],
    knowledgeNodeIds: ['doc:testing-rollback']
  }),
  createStudyRecord({
    id: 'study-code-ownership',
    title: 'Code Ownership',
    category: 'governance',
    summary: 'A clear mapping between code areas and accountable owners.',
    what: 'Code ownership assigns responsibility for review, maintenance, and escalation.',
    why: 'It reduces ambiguity and keeps changes from drifting without stewardship.',
    whenToUse: 'Use when a module, route, or service needs a clear maintainer.',
    whenNotToUse: 'Do not use to create bottlenecks or hidden gatekeeping.',
    prerequisites: ['Defined module boundaries', 'Owner list', 'Review protocol'],
    implementationMethod: 'Assign ownership by folder or service and reflect it in reviews and alerts.',
    verificationMethod: 'Confirm each major area has an active owner and backup.',
    rollbackMethod: 'Reassign ownership back to a wider team if the map becomes too narrow.',
    tradeoffs: ['More explicit responsibility', 'Less ambiguity'],
    risks: ['Ownership silos if no backup exists'],
    evidence: ['Engineering review and stewardship practices'],
    sources: [
      { title: 'Google Engineering Practices', url: 'https://google.github.io/eng-practices/', tier: 'tier2', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['engineering', 'governance'],
    affectedServices: ['modules'],
    expectedOutcome: 'Every important area has a named steward.',
    measurableIndicators: ['Review routing improves', 'Stale areas shrink'],
    recommendation: 'watch',
    confidence: 86,
    status: 'verified',
    relatedSkillIds: ['code-ownership'],
    knowledgeNodeIds: ['doc:code-ownership']
  }),
  createStudyRecord({
    id: 'study-pr-governance',
    title: 'Pull Request Governance',
    category: 'governance',
    summary: 'A repeatable set of review and approval rules for code changes.',
    what: 'PR governance defines who can review, approve, merge, and block changes.',
    why: 'It makes change control explicit and auditable.',
    whenToUse: 'Use on all shared repositories and production-impacting changes.',
    whenNotToUse: 'Do not use if it will slow urgent fixes without a bypass rule.',
    prerequisites: ['Branch rules', 'Reviewers', 'Approval criteria'],
    implementationMethod: 'Apply protection rules, require review, and keep merge criteria visible.',
    verificationMethod: 'Confirm a change cannot land without the expected approvals.',
    rollbackMethod: 'Revert the merge and tighten the blocked criteria if needed.',
    tradeoffs: ['More process', 'Better safety'],
    risks: ['Review bottlenecks if owners are unavailable'],
    evidence: ['Branch protection and review governance practices'],
    sources: [
      { title: 'GitHub Docs', url: 'https://docs.github.com/', tier: 'tier1', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['engineering', 'release'],
    affectedServices: ['pull-requests'],
    expectedOutcome: 'Changes move through explicit approval gates.',
    measurableIndicators: ['Unreviewed merges fall', 'Approval latency is visible'],
    recommendation: 'pilot',
    confidence: 93,
    status: 'verified',
    relatedSkillIds: ['pull-request-governance'],
    knowledgeNodeIds: ['doc:pr-governance']
  }),
  createStudyRecord({
    id: 'study-technical-debt',
    title: 'Technical Debt Management',
    category: 'governance',
    summary: 'A structured way to track, classify, and retire accumulated friction.',
    what: 'Technical debt management surfaces cost, priority, and payoff.',
    why: 'It keeps debt visible instead of letting it silently compound.',
    whenToUse: 'Use when repeated friction, duplication, or brittle code affects delivery.',
    whenNotToUse: 'Do not use as a label for normal unfinished work.',
    prerequisites: ['Debt inventory', 'Impact estimate', 'Owner or sponsor'],
    implementationMethod: 'Classify debt by impact, attach it to a backlog, and revisit it on a schedule.',
    verificationMethod: 'Confirm debt items have owners, states, and measurable reduction progress.',
    rollbackMethod: 'Pause debt work only if it is crowding out critical recovery or launch work.',
    tradeoffs: ['Requires maintenance discipline', 'Improves long-term speed'],
    risks: ['Debt can be under-prioritized if not scored'],
    evidence: ['Debt review patterns and engineering backlog hygiene'],
    sources: [
      { title: 'Microsoft Engineering Docs', url: 'https://microsoft.github.io/code-with-engineering-playbook/', tier: 'tier2', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['engineering', 'planning'],
    affectedServices: ['backlog'],
    expectedOutcome: 'Debt becomes visible, prioritizable, and burn-downable.',
    measurableIndicators: ['Debt count falls', 'Rework time falls'],
    recommendation: 'watch',
    confidence: 85,
    status: 'verified',
    relatedSkillIds: ['technical-debt-management'],
    knowledgeNodeIds: ['doc:technical-debt']
  }),
  createStudyRecord({
    id: 'study-docs-code',
    title: 'Documentation as Code',
    category: 'documentation',
    summary: 'Treat documentation as a versioned, reviewable, testable artifact.',
    what: 'Docs live beside code, change with code, and can be reviewed with code.',
    why: 'It reduces drift and keeps documentation current.',
    whenToUse: 'Use for runbooks, specs, decision logs, and operational notes.',
    whenNotToUse: 'Do not use when external publishing systems require a separate authoring path.',
    prerequisites: ['Version control', 'Review process', 'Doc ownership'],
    implementationMethod: 'Store docs in the repo, require review, and tie changes to code or workflow updates.',
    verificationMethod: 'Confirm docs are updated when the associated behavior changes.',
    rollbackMethod: 'Revert the documentation commit or update the stale section to the previous truth.',
    tradeoffs: ['More repo content', 'Less doc drift'],
    risks: ['Documentation can still lag if ownership is unclear'],
    evidence: ['Repo-based governance and review workflows'],
    sources: [
      { title: 'GitHub Docs', url: 'https://docs.github.com/', tier: 'tier1', retrievedAt: '2026-07-11T00:00:00.000Z', sourceType: 'official' }
    ],
    affectedWorkspaces: ['documentation', 'engineering'],
    affectedServices: ['docs'],
    expectedOutcome: 'Docs stay close to the code and workflow reality.',
    measurableIndicators: ['Doc drift decreases', 'Review velocity stays high'],
    recommendation: 'adopt',
    confidence: 94,
    status: 'verified',
    relatedSkillIds: ['documentation-as-code'],
    knowledgeNodeIds: ['doc:docs-as-code']
  })
];
